#!/bin/bash

cp ../../../build.debug/mtest/libmscore/rhythmicGrouping/group8ths4-4.mscx      group8ths4-4-ref.mscx
cp ../../../build.debug/mtest/libmscore/rhythmicGrouping/group8thsSimple.mscx   group8thsSimple-ref.mscx
cp ../../../build.debug/mtest/libmscore/rhythmicGrouping/group8thsCompound.mscx group8thsCompound-ref.mscx
cp ../../../build.debug/mtest/libmscore/rhythmicGrouping/groupSubbeats.mscx     groupSubbeats-ref.mscx
cp ../../../build.debug/mtest/libmscore/rhythmicGrouping/groupVoices.mscx       groupVoices-ref.mscx
cp ../../../build.debug/mtest/libmscore/rhythmicGrouping/groupConflicts.mscx    groupConflicts-ref.mscx
cp ../../../build.debug/mtest/libmscore/rhythmicGrouping/groupArticulationsTies.mscx    groupArticulationsTies-ref.mscx

