<?xml version="1.0" encoding="UTF-8"?>
<museScore version="3.02">
  <Style>
    <lyricsOddFontFace>Edwin</lyricsOddFontFace>
    <lyricsOddFontSize>10</lyricsOddFontSize>
    <lyricsEvenFontFace>Edwin</lyricsEvenFontFace>
    <lyricsEvenFontSize>10</lyricsEvenFontSize>
    <hairpinFontFace>Edwin</hairpinFontFace>
    <hairpinFontSize>10</hairpinFontSize>
    <pedalFontFace>Edwin</pedalFontFace>
    <chordSymbolAFontFace>Edwin</chordSymbolAFontFace>
    <chordSymbolAFontSize>11</chordSymbolAFontSize>
    <chordSymbolBFontFace>Edwin</chordSymbolBFontFace>
    <chordSymbolBFontSize>11</chordSymbolBFontSize>
    <nashvilleNumberFontFace>Edwin</nashvilleNumberFontFace>
    <ottavaFontFace>Edwin</ottavaFontFace>
    <tupletFontFace>Edwin</tupletFontFace>
    <tupletFontSize>9</tupletFontSize>
    <tupletFontStyle>3</tupletFontStyle>
    <defaultFontFace>Edwin</defaultFontFace>
    <titleFontFace>Edwin</titleFontFace>
    <subTitleFontFace>Edwin</subTitleFontFace>
    <subTitleFontSize>18</subTitleFontSize>
    <composerFontFace>Edwin</composerFontFace>
    <composerFontSize>11</composerFontSize>
    <lyricistFontFace>Edwin</lyricistFontFace>
    <lyricistFontSize>11</lyricistFontSize>
    <fingeringFontFace>Edwin</fingeringFontFace>
    <lhGuitarFingeringFontFace>Edwin</lhGuitarFingeringFontFace>
    <rhGuitarFingeringFontFace>Edwin</rhGuitarFingeringFontFace>
    <stringNumberFontFace>Edwin</stringNumberFontFace>
    <longInstrumentFontFace>Edwin</longInstrumentFontFace>
    <longInstrumentFontSize>10</longInstrumentFontSize>
    <shortInstrumentFontFace>Edwin</shortInstrumentFontFace>
    <shortInstrumentFontSize>10</shortInstrumentFontSize>
    <partInstrumentFontFace>Edwin</partInstrumentFontFace>
    <partInstrumentFontSize>14</partInstrumentFontSize>
    <dynamicsFontFace>Edwin</dynamicsFontFace>
    <dynamicsFontSize>11</dynamicsFontSize>
    <expressionFontFace>Edwin</expressionFontFace>
    <expressionFontSize>10</expressionFontSize>
    <tempoFontFace>Edwin</tempoFontFace>
    <tempoFontSize>12</tempoFontSize>
    <metronomeFontFace>Edwin</metronomeFontFace>
    <metronomeFontSize>10</metronomeFontSize>
    <measureNumberFontFace>Edwin</measureNumberFontFace>
    <measureNumberFontSize>9</measureNumberFontSize>
    <measureNumberFontStyle>2</measureNumberFontStyle>
    <measureNumberAlign>left,baseline</measureNumberAlign>
    <translatorFontFace>Edwin</translatorFontFace>
    <translatorFontSize>10</translatorFontSize>
    <systemFontFace>Edwin</systemFontFace>
    <staffFontFace>Edwin</staffFontFace>
    <rehearsalMarkFontFace>Edwin</rehearsalMarkFontFace>
    <rehearsalMarkFontSize>14</rehearsalMarkFontSize>
    <repeatLeftFontFace>Edwin</repeatLeftFontFace>
    <repeatRightFontFace>Edwin</repeatRightFontFace>
    <frameFontFace>Edwin</frameFontFace>
    <textLineFontFace>Edwin</textLineFontFace>
    <glissandoFontFace>Edwin</glissandoFontFace>
    <bendFontFace>Edwin</bendFontFace>
    <headerFontFace>Edwin</headerFontFace>
    <headerFontSize>9</headerFontSize>
    <footerFontFace>Edwin</footerFontFace>
    <footerFontSize>9</footerFontSize>
    <instrumentChangeFontFace>Edwin</instrumentChangeFontFace>
    <stickingFontFace>Edwin</stickingFontFace>
    <stickingFontSize>10</stickingFontSize>
    <user1FontFace>Edwin</user1FontFace>
    <user2FontFace>Edwin</user2FontFace>
    <user3FontFace>Edwin</user3FontFace>
    <user4FontFace>Edwin</user4FontFace>
    <user5FontFace>Edwin</user5FontFace>
    <user6FontFace>Edwin</user6FontFace>
    <user7FontFace>Edwin</user7FontFace>
    <user8FontFace>Edwin</user8FontFace>
    <user9FontFace>Edwin</user9FontFace>
    <user10FontFace>Edwin</user10FontFace>
    <user11FontFace>Edwin</user11FontFace>
    <user12FontFace>Edwin</user12FontFace>
    <letRingFontFace>Edwin</letRingFontFace>
    <palmMuteFontFace>Edwin</palmMuteFontFace>
    </Style>
  </museScore>
