<?xml version="1.0" encoding="UTF-8"?>
<museScore version="3.02">
  <Style>
    <maxSystemDistance>17</maxSystemDistance>
    <lyricsOddFontFace>Edwin</lyricsOddFontFace>
    <lyricsOddFontSize>10</lyricsOddFontSize>
    <lyricsEvenFontFace>Edwin</lyricsEvenFontFace>
    <lyricsEvenFontSize>10</lyricsEvenFontSize>
    <barWidth>0.18</barWidth>
    <doubleBarWidth>0.18</doubleBarWidth>
    <endBarWidth>0.55</endBarWidth>
    <doubleBarDistance>0.55</doubleBarDistance>
    <endBarDistance>0.915</endBarDistance>
    <repeatBarlineDotSeparation>0.7</repeatBarlineDotSeparation>
    <bracketWidth>0.44</bracketWidth>
    <clefLeftMargin>0.75</clefLeftMargin>
    <keysigLeftMargin>0.75</keysigLeftMargin>
    <timesigLeftMargin>0.75</timesigLeftMargin>
    <midClefKeyRightMargin>1.4</midClefKeyRightMargin>
    <clefKeyDistance>0.75</clefKeyDistance>
    <clefTimesigDistance>0.9</clefTimesigDistance>
    <systemHeaderDistance>3</systemHeaderDistance>
    <systemHeaderTimeSigDistance>2.5</systemHeaderTimeSigDistance>
    <clefBarlineDistance>0.9</clefBarlineDistance>
    <timesigBarlineDistance>0.75</timesigBarlineDistance>
    <stemWidth>0.11</stemWidth>
    <minNoteDistance>0.1</minNoteDistance>
    <barNoteDistance>1.35</barNoteDistance>
    <barAccidentalDistance>0.7</barAccidentalDistance>
    <multiMeasureRestMargin>1.35</multiMeasureRestMargin>
    <noteBarDistance>1.75</noteBarDistance>
    <measureSpacing>1.5</measureSpacing>
    <staffLineWidth>0.11</staffLineWidth>
    <ledgerLineLength>0.55</ledgerLineLength>
    <accidentalDistance>0.3</accidentalDistance>
    <accidentalNoteDistance>0.3</accidentalNoteDistance>
    <beamMinLen>1.3</beamMinLen>
    <dotNoteDistance>0.6</dotNoteDistance>
    <dotDotDistance>0.75</dotDotDistance>
    <hairpinHeight>1.15</hairpinHeight>
    <hairpinWidth>0.12</hairpinWidth>
    <hairpinFontFace>Edwin</hairpinFontFace>
    <hairpinFontSize>10</hairpinFontSize>
    <pedalLineWidth>0.11</pedalLineWidth>
    <pedalFontFace>Edwin</pedalFontFace>
    <chordSymbolAFontFace>Edwin</chordSymbolAFontFace>
    <chordSymbolBFontFace>Edwin</chordSymbolBFontFace>
    <chordSymbolBFontSize>10</chordSymbolBFontSize>
    <nashvilleNumberFontFace>Edwin</nashvilleNumberFontFace>
    <enableIndentationOnFirstSystem>1</enableIndentationOnFirstSystem>
    <slurEndWidth>0.05</slurEndWidth>
    <slurMidWidth>0.18</slurMidWidth>
    <musicalSymbolFont>Leland</musicalSymbolFont>
    <musicalTextFont>Leland Text</musicalTextFont>
    <showHeader>1</showHeader>
    <evenHeaderL>$p</evenHeaderL>
    <oddHeaderR>$p</oddHeaderR>
    <evenFooterL></evenFooterL>
    <oddFooterR></oddFooterR>
    <voltaLineWidth>0.11</voltaLineWidth>
    <voltaFontFace>Edwin</voltaFontFace>
    <ottavaLineWidth>0.11</ottavaLineWidth>
    <ottavaFontFace>Edwin</ottavaFontFace>
    <tupletVStemDistance>0.5</tupletVStemDistance>
    <tupletStemLeftDistance>0</tupletStemLeftDistance>
    <tupletNoteLeftDistance>-0.5</tupletNoteLeftDistance>
    <tupletFontFace>Edwin</tupletFontFace>
    <tupletFontStyle>3</tupletFontStyle>
    <tupletBracketHookHeight>0.75</tupletBracketHookHeight>
    <barGraceDistance>1.35</barGraceDistance>
    <dynamicsPosAbove x="0" y="-1.5"/>
    <dynamicsPosBelow x="0" y="2.5"/>
    <defaultFontFace>Edwin</defaultFontFace>
    <titleFontFace>Edwin</titleFontFace>
    <subTitleFontFace>Edwin</subTitleFontFace>
    <composerFontFace>Edwin</composerFontFace>
    <composerFontSize>10</composerFontSize>
    <lyricistFontFace>Edwin</lyricistFontFace>
    <fingeringFontFace>Edwin</fingeringFontFace>
    <lhGuitarFingeringFontFace>Edwin</lhGuitarFingeringFontFace>
    <rhGuitarFingeringFontFace>Edwin</rhGuitarFingeringFontFace>
    <stringNumberFontFace>Edwin</stringNumberFontFace>
    <longInstrumentFontFace>Edwin</longInstrumentFontFace>
    <longInstrumentFontSize>10</longInstrumentFontSize>
    <shortInstrumentFontFace>Edwin</shortInstrumentFontFace>
    <shortInstrumentFontSize>10</shortInstrumentFontSize>
    <partInstrumentFontFace>Edwin</partInstrumentFontFace>
    <dynamicsFontFace>Edwin</dynamicsFontFace>
    <dynamicsFontSize>11</dynamicsFontSize>
    <expressionFontFace>Edwin</expressionFontFace>
    <expressionFontSize>10</expressionFontSize>
    <tempoFontFace>Edwin</tempoFontFace>
    <metronomeFontFace>Edwin</metronomeFontFace>
    <measureNumberFontFace>Edwin</measureNumberFontFace>
    <measureNumberFontSize>9</measureNumberFontSize>
    <measureNumberFontStyle>2</measureNumberFontStyle>
    <translatorFontFace>Edwin</translatorFontFace>
    <systemFontFace>Edwin</systemFontFace>
    <staffFontFace>Edwin</staffFontFace>
    <staffPosBelow x="0" y="2"/>
    <rehearsalMarkFontFace>Edwin</rehearsalMarkFontFace>
    <repeatLeftFontFace>Edwin</repeatLeftFontFace>
    <repeatRightFontFace>Edwin</repeatRightFontFace>
    <frameFontFace>Edwin</frameFontFace>
    <textLineFontFace>Edwin</textLineFontFace>
    <glissandoFontFace>Edwin</glissandoFontFace>
    <bendFontFace>Edwin</bendFontFace>
    <headerFontFace>Edwin</headerFontFace>
    <headerFontSize>10</headerFontSize>
    <headerFontStyle>1</headerFontStyle>
    <footerFontFace>Edwin</footerFontFace>
    <footerFontSize>9</footerFontSize>
    <instrumentChangeFontFace>Edwin</instrumentChangeFontFace>
    <stickingFontFace>Edwin</stickingFontFace>
    <user1FontFace>Edwin</user1FontFace>
    <user2FontFace>Edwin</user2FontFace>
    <user3FontFace>Edwin</user3FontFace>
    <user4FontFace>Edwin</user4FontFace>
    <user5FontFace>Edwin</user5FontFace>
    <user6FontFace>Edwin</user6FontFace>
    <user7FontFace>Edwin</user7FontFace>
    <user8FontFace>Edwin</user8FontFace>
    <user9FontFace>Edwin</user9FontFace>
    <user10FontFace>Edwin</user10FontFace>
    <user11FontFace>Edwin</user11FontFace>
    <user12FontFace>Edwin</user12FontFace>
    <letRingFontFace>Edwin</letRingFontFace>
    <palmMuteFontFace>Edwin</palmMuteFontFace>
    <fermataPosAbove x="0" y="-0.5"/>
    <fermataPosBelow x="0" y="0.5"/>
    <qualityUpgradeAllowed>1</qualityUpgradeAllowed>
    </Style>
  </museScore>
