<?xml version="1.0" encoding="UTF-8"?>
<museScore version="3.02">
  <Style>
    <maxSystemDistance>15</maxSystemDistance>
    <lyricsOddFontFace>FreeSerif</lyricsOddFontFace>
    <lyricsOddFontSize>11</lyricsOddFontSize>
    <lyricsEvenFontFace>FreeSerif</lyricsEvenFontFace>
    <lyricsEvenFontSize>11</lyricsEvenFontSize>
    <barWidth>0.16</barWidth>
    <doubleBarWidth>0.16</doubleBarWidth>
    <endBarWidth>0.5</endBarWidth>
    <doubleBarDistance>0.56</doubleBarDistance>
    <endBarDistance>0.73</endBarDistance>
    <repeatBarlineDotSeparation>0.63</repeatBarlineDotSeparation>
    <bracketWidth>0.45</bracketWidth>
    <clefLeftMargin>0.8</clefLeftMargin>
    <keysigLeftMargin>0.5</keysigLeftMargin>
    <timesigLeftMargin>0.5</timesigLeftMargin>
    <midClefKeyRightMargin>1</midClefKeyRightMargin>
    <clefKeyDistance>1</clefKeyDistance>
    <clefTimesigDistance>1</clefTimesigDistance>
    <systemHeaderDistance>2.5</systemHeaderDistance>
    <systemHeaderTimeSigDistance>2</systemHeaderTimeSigDistance>
    <clefBarlineDistance>0.5</clefBarlineDistance>
    <timesigBarlineDistance>0.5</timesigBarlineDistance>
    <stemWidth>0.13</stemWidth>
    <minNoteDistance>0.25</minNoteDistance>
    <barNoteDistance>1</barNoteDistance>
    <barAccidentalDistance>0.3</barAccidentalDistance>
    <multiMeasureRestMargin>1.2</multiMeasureRestMargin>
    <noteBarDistance>1</noteBarDistance>
    <measureSpacing>1.2</measureSpacing>
    <staffLineWidth>0.08</staffLineWidth>
    <ledgerLineLength>0.6</ledgerLineLength>
    <accidentalDistance>0.22</accidentalDistance>
    <accidentalNoteDistance>0.22</accidentalNoteDistance>
    <beamMinLen>1.32</beamMinLen>
    <dotNoteDistance>0.35</dotNoteDistance>
    <dotDotDistance>0.5</dotDotDistance>
    <hairpinHeight>1.2</hairpinHeight>
    <hairpinWidth>0.13</hairpinWidth>
    <hairpinFontFace>FreeSerif</hairpinFontFace>
    <hairpinFontSize>12</hairpinFontSize>
    <pedalLineWidth>0.15</pedalLineWidth>
    <pedalFontFace>FreeSerif</pedalFontFace>
    <chordSymbolAFontFace>FreeSerif</chordSymbolAFontFace>
    <chordSymbolBFontFace>FreeSerif</chordSymbolBFontFace>
    <chordSymbolBFontSize>12</chordSymbolBFontSize>
    <nashvilleNumberFontFace>FreeSerif</nashvilleNumberFontFace>
    <enableIndentationOnFirstSystem>0</enableIndentationOnFirstSystem>
    <slurEndWidth>0.07</slurEndWidth>
    <slurMidWidth>0.15</slurMidWidth>
    <musicalSymbolFont>Emmentaler</musicalSymbolFont>
    <musicalTextFont>MScore Text</musicalTextFont>
    <showHeader>0</showHeader>
    <evenHeaderL></evenHeaderL>
    <oddHeaderR></oddHeaderR>
    <evenFooterL>$p</evenFooterL>
    <oddFooterR>$p</oddFooterR>
    <voltaLineWidth>0.1</voltaLineWidth>
    <voltaFontFace>FreeSerif</voltaFontFace>
    <ottavaLineWidth>0.1</ottavaLineWidth>
    <ottavaFontFace>FreeSerif</ottavaFontFace>
    <tupletVStemDistance>0.25</tupletVStemDistance>
    <tupletStemLeftDistance>0.5</tupletStemLeftDistance>
    <tupletNoteLeftDistance>0</tupletNoteLeftDistance>
    <tupletFontFace>FreeSerif</tupletFontFace>
    <tupletFontStyle>2</tupletFontStyle>
    <tupletBracketHookHeight>1</tupletBracketHookHeight>
    <barGraceDistance>0.6</barGraceDistance>
    <dynamicsPosAbove x="0" y="-3"/>
    <dynamicsPosBelow x="0" y="4"/>
    <defaultFontFace>FreeSerif</defaultFontFace>
    <titleFontFace>FreeSerif</titleFontFace>
    <subTitleFontFace>FreeSerif</subTitleFontFace>
    <composerFontFace>FreeSerif</composerFontFace>
    <composerFontSize>12</composerFontSize>
    <lyricistFontFace>FreeSerif</lyricistFontFace>
    <fingeringFontFace>FreeSerif</fingeringFontFace>
    <lhGuitarFingeringFontFace>FreeSerif</lhGuitarFingeringFontFace>
    <rhGuitarFingeringFontFace>FreeSerif</rhGuitarFingeringFontFace>
    <stringNumberFontFace>FreeSerif</stringNumberFontFace>
    <longInstrumentFontFace>FreeSerif</longInstrumentFontFace>
    <longInstrumentFontSize>12</longInstrumentFontSize>
    <shortInstrumentFontFace>FreeSerif</shortInstrumentFontFace>
    <shortInstrumentFontSize>12</shortInstrumentFontSize>
    <partInstrumentFontFace>FreeSerif</partInstrumentFontFace>
    <dynamicsFontFace>FreeSerif</dynamicsFontFace>
    <dynamicsFontSize>12</dynamicsFontSize>
    <expressionFontFace>FreeSerif</expressionFontFace>
    <expressionFontSize>11</expressionFontSize>
    <tempoFontFace>FreeSerif</tempoFontFace>
    <metronomeFontFace>FreeSerif</metronomeFontFace>
    <measureNumberFontFace>FreeSerif</measureNumberFontFace>
    <measureNumberFontSize>8</measureNumberFontSize>
    <measureNumberFontStyle>0</measureNumberFontStyle>
    <translatorFontFace>FreeSerif</translatorFontFace>
    <systemFontFace>FreeSerif</systemFontFace>
    <staffFontFace>FreeSerif</staffFontFace>
    <staffPosBelow x="0" y="3.5"/>
    <rehearsalMarkFontFace>FreeSerif</rehearsalMarkFontFace>
    <repeatLeftFontFace>FreeSerif</repeatLeftFontFace>
    <repeatRightFontFace>FreeSerif</repeatRightFontFace>
    <frameFontFace>FreeSerif</frameFontFace>
    <textLineFontFace>FreeSerif</textLineFontFace>
    <glissandoFontFace>FreeSerif</glissandoFontFace>
    <bendFontFace>FreeSerif</bendFontFace>
    <headerFontFace>FreeSerif</headerFontFace>
    <headerFontSize>8</headerFontSize>
    <headerFontStyle>0</headerFontStyle>
    <footerFontFace>FreeSerif</footerFontFace>
    <footerFontSize>8</footerFontSize>
    <instrumentChangeFontFace>FreeSerif</instrumentChangeFontFace>
    <stickingFontFace>FreeSerif</stickingFontFace>
    <user1FontFace>FreeSerif</user1FontFace>
    <user2FontFace>FreeSerif</user2FontFace>
    <user3FontFace>FreeSerif</user3FontFace>
    <user4FontFace>FreeSerif</user4FontFace>
    <user5FontFace>FreeSerif</user5FontFace>
    <user6FontFace>FreeSerif</user6FontFace>
    <user7FontFace>FreeSerif</user7FontFace>
    <user8FontFace>FreeSerif</user8FontFace>
    <user9FontFace>FreeSerif</user9FontFace>
    <user10FontFace>FreeSerif</user10FontFace>
    <user11FontFace>FreeSerif</user11FontFace>
    <user12FontFace>FreeSerif</user12FontFace>
    <letRingFontFace>FreeSerif</letRingFontFace>
    <palmMuteFontFace>FreeSerif</palmMuteFontFace>
    <fermataPosAbove x="0" y="-1"/>
    <fermataPosBelow x="0" y="1"/>
    <qualityUpgradeAllowed>0</qualityUpgradeAllowed>
    </Style>
  </museScore>
