
set (MUSICXML_SRC
    ${CMAKE_CURRENT_LIST_DIR}/exportxml.cpp
    ${CMAKE_CURRENT_LIST_DIR}/exportxml.h
    ${CMAKE_CURRENT_LIST_DIR}/importmxml.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmxml.h
    ${CMAKE_CURRENT_LIST_DIR}/importmxmllogger.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmxmllogger.h
    ${CMAKE_CURRENT_LIST_DIR}/importmxmlnoteduration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmxmlnoteduration.h
    ${CMAKE_CURRENT_LIST_DIR}/importmxmlnotepitch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmxmlnotepitch.h
    ${CMAKE_CURRENT_LIST_DIR}/importmxmlpass1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmxmlpass1.h
    ${CMAKE_CURRENT_LIST_DIR}/importmxmlpass2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmxmlpass2.h
    ${CMAKE_CURRENT_LIST_DIR}/importxml.cpp
    ${CMAKE_CURRENT_LIST_DIR}/musicxmlfonthandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/musicxmlfonthandler.h
    ${CMAKE_CURRENT_LIST_DIR}/musicxmlpart.cpp
    ${CMAKE_CURRENT_LIST_DIR}/musicxmlpart.h
    ${CMAKE_CURRENT_LIST_DIR}/musicxmlsupport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/musicxmlsupport.h
    ${CMAKE_CURRENT_LIST_DIR}/musicxmltupletstate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/musicxmltupletstate.h
    ${CMAKE_CURRENT_LIST_DIR}/musicxmltypes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/musicxmltypes.h
    ${CMAKE_CURRENT_LIST_DIR}/musicxmlvalidation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/musicxmlvalidation.h
    ${CMAKE_CURRENT_LIST_DIR}/musicxmlvoicedesc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/musicxmlvoicedesc.h
    )
