//=============================================================================
//  MusE Score
//  Linux Music Score Editor
//
//  Copyright (C) 2014 Werner Schweer and others
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License version 2.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//=============================================================================

/**
 MusicXML font handling support.
 */

#include "musicxmlfonthandler.h"

namespace Ms {

static QString charFormat2QString(const CharFormat& f)
      {
      return QString("b %1 i %2 u %3 va %4 fs %5 fam %6")
            .arg(f.bold())
            .arg(f.italic())
            .arg(f.underline())
            .arg(static_cast<int>(f.valign()))
            .arg(f.fontSize())
            .arg(f.fontFamily())
                 ;
      }

//---------------------------------------------------------
//   MScoreTextToMXML
//    Convert rich text as generated by Text::text()
//    into MusicXML text with formatting
//---------------------------------------------------------

MScoreTextToMXML::MScoreTextToMXML(const QString& t)
      {
      text = "<dummy>" + t + "</dummy>"; // convert text into valid xml
      qDebug("MScoreTextToMXML('%s')", qPrintable(t));
      }

void MScoreTextToMXML::parse()
      {
      qDebug("MScoreTextToMXML::parse()");
      QXmlStreamReader r(text);
      while (!r.atEnd()) {
            // do processing
            r.readNext();
            if(r.isCharacters()) {
                  qDebug("old %s", qPrintable(charFormat2QString(oldFormat)));
                  qDebug("new %s", qPrintable(charFormat2QString(newFormat)));
                  updateFormat();
                  qDebug("old %s", qPrintable(charFormat2QString(oldFormat)));
                  qDebug("new %s", qPrintable(charFormat2QString(newFormat)));
                  qDebug("Characters '%s'", qPrintable(r.text().toString()));
            }
            else if(r.isEndElement()) {
                  qDebug("EndElem '%s'", qPrintable(r.name().toString()));
                  handleEndElement(r);
                  }
            else if(r.isStartElement()) {
                  qDebug("StartElem '%s'", qPrintable(r.name().toString()));
                  if (r.name() == "font")
                        qDebug("   face='%s' size='%s'",
                               qPrintable(r.attributes().value("face").toString()),
                               qPrintable(r.attributes().value("size").toString()));
                  handleStartElement(r);
                  }
            }
      if (r.hasError()) {
            // do error handling
            qDebug("Error %s", qPrintable(r.errorString()));
            }
      }
      
void MScoreTextToMXML::handleStartElement(QXmlStreamReader& r)
{
      if (r.name() == "b")
            newFormat.setBold(true);
      else if (r.name() == "i")
            newFormat.setItalic(true);
      else if (r.name() == "u")
            newFormat.setUnderline(true);
      else if (r.name() == "font" && r.attributes().hasAttribute("size"))
            newFormat.setFontSize(r.attributes().value("size").toFloat());
      else if (r.name() == "font" && r.attributes().hasAttribute("face"))
            newFormat.setFontFamily(r.attributes().value("face").toString());
      else if (r.name() == "sub")
            ; // ignore (TODO)
      else if (r.name() == "sup")
            ; // ignore (TODO)
      else if (r.name() == "sym")
            // ignore (TODO)
            r.skipCurrentElement();
      else if (r.name() == "dummy")
            ; // ignore
      else {
            qDebug("handleStartElem '%s' unknown", qPrintable(r.name().toString()));
            r.skipCurrentElement();
      }
}
      
void MScoreTextToMXML::handleEndElement(QXmlStreamReader& r)
{
      if (r.name() == "b")
            newFormat.setBold(false);
      else if (r.name() == "i")
            newFormat.setItalic(false);
      else if (r.name() == "u")
            newFormat.setUnderline(false);
      else if (r.name() == "font")
            ; // ignore
      else if (r.name() == "sub")
            ; // ignore (TODO)
      else if (r.name() == "sup")
            ; // ignore (TODO)
      else if (r.name() == "sym")
            ; // ignore (TODO)
      else if (r.name() == "dummy")
            ; // ignore
      else {
            qDebug("handleEndElem '%s' unknown", qPrintable(r.name().toString()));
            r.skipCurrentElement();
      }
}

static QString attribute(bool needed, bool value, QString trueString, QString falseString)
      {
      QString res;
      if (needed)
            res = value ? trueString : falseString;
      if (res != "")
            res = " " + res;
      return res;
      }

//---------------------------------------------------------
//   updateFormat
//    update the text format by generating attributes
//    corresponding to the difference between old- and newFormat
//    copy newFormat to oldFormat
//---------------------------------------------------------

QString MScoreTextToMXML::updateFormat()
      {
      QString res;
      res += attribute(newFormat.bold() != oldFormat.bold(), newFormat.bold(), "font-weight=\"bold\"", "font-weight=\"normal\"");
      res += attribute(newFormat.italic() != oldFormat.italic(), newFormat.italic(), "font-style=\"italic\"", "font-style=\"normal\"");
      res += attribute(newFormat.underline() != oldFormat.underline(), newFormat.underline(), "underline=\"1\"", "underline=\"0\"");
      res += attribute(newFormat.fontFamily() != oldFormat.fontFamily(), true, QString("font-family=\"%1\"").arg(newFormat.fontFamily()), "");
      bool needSize = newFormat.fontSize() < 0.99 * oldFormat.fontSize() || newFormat.fontSize() > 1.01 * oldFormat.fontSize();
      res += attribute(needSize, true, QString("font-size=\"%1\"").arg(newFormat.fontSize()), "");
      qDebug("updateFormat() res '%s'", qPrintable(res));
      oldFormat = newFormat;
      return "";
      }

} // namespace Ms
