
set (WIDGETS_UI
    ${CMAKE_CURRENT_LIST_DIR}/measureproperties.ui
    ${CMAKE_CURRENT_LIST_DIR}/editstyle.ui
    ${CMAKE_CURRENT_LIST_DIR}/align_select.ui
    ${CMAKE_CURRENT_LIST_DIR}/font_style_select.ui
    ${CMAKE_CURRENT_LIST_DIR}/offset_select.ui
    ${CMAKE_CURRENT_LIST_DIR}/editstaff.ui
    ${CMAKE_CURRENT_LIST_DIR}/editstafftype.ui
    ${CMAKE_CURRENT_LIST_DIR}/editstringdata.ui
    ${CMAKE_CURRENT_LIST_DIR}/editpitch.ui
    ${CMAKE_CURRENT_LIST_DIR}/breaksdialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/pagebreaksdialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/pagesettings.ui
    ${CMAKE_CURRENT_LIST_DIR}/transposedialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/selectnotedialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/selectdialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/tupletdialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/voicing_select.ui
    ${CMAKE_CURRENT_LIST_DIR}/stafftextpropertiesdialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/realizeharmonydialog.ui
    )

set(WIDGETS_SRC
    ${CMAKE_CURRENT_LIST_DIR}/measureproperties.cpp
    ${CMAKE_CURRENT_LIST_DIR}/measureproperties.h
    ${CMAKE_CURRENT_LIST_DIR}/editstyle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/editstyle.h
    ${CMAKE_CURRENT_LIST_DIR}/alignSelect.cpp
    ${CMAKE_CURRENT_LIST_DIR}/alignSelect.h
    ${CMAKE_CURRENT_LIST_DIR}/colorlabel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/colorlabel.h
    ${CMAKE_CURRENT_LIST_DIR}/fontStyleSelect.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fontStyleSelect.h
    ${CMAKE_CURRENT_LIST_DIR}/offsetSelect.cpp
    ${CMAKE_CURRENT_LIST_DIR}/offsetSelect.h
    ${CMAKE_CURRENT_LIST_DIR}/editstaff.cpp
    ${CMAKE_CURRENT_LIST_DIR}/editstaff.h
    ${CMAKE_CURRENT_LIST_DIR}/editstafftype.cpp
    ${CMAKE_CURRENT_LIST_DIR}/editstafftype.h
    ${CMAKE_CURRENT_LIST_DIR}/editstringdata.cpp
    ${CMAKE_CURRENT_LIST_DIR}/editstringdata.h
    ${CMAKE_CURRENT_LIST_DIR}/editpitch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/editpitch.h
    ${CMAKE_CURRENT_LIST_DIR}/exampleview.cpp
    ${CMAKE_CURRENT_LIST_DIR}/exampleview.h
    ${CMAKE_CURRENT_LIST_DIR}/breaksdialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/breaksdialog.h
    ${CMAKE_CURRENT_LIST_DIR}/pagebreaksdialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pagebreaksdialog.h
    ${CMAKE_CURRENT_LIST_DIR}/pagesettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pagesettings.h
    ${CMAKE_CURRENT_LIST_DIR}/transposedialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transposedialog.h
    ${CMAKE_CURRENT_LIST_DIR}/selectnotedialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/selectnotedialog.h
    ${CMAKE_CURRENT_LIST_DIR}/selectdialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/selectdialog.h
    ${CMAKE_CURRENT_LIST_DIR}/tupletdialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/tupletdialog.h
    ${CMAKE_CURRENT_LIST_DIR}/voicingSelect.cpp
    ${CMAKE_CURRENT_LIST_DIR}/voicingSelect.h
    ${CMAKE_CURRENT_LIST_DIR}/stafftextpropertiesdialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/stafftextpropertiesdialog.h
    ${CMAKE_CURRENT_LIST_DIR}/timelineview.cpp
    ${CMAKE_CURRENT_LIST_DIR}/timelineview.h
    ${CMAKE_CURRENT_LIST_DIR}/timeline.cpp
    ${CMAKE_CURRENT_LIST_DIR}/timeline.h
    ${CMAKE_CURRENT_LIST_DIR}/realizeharmonydialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/realizeharmonydialog.h
    )
