set(STYLEDIALOG_SRC
    ${CMAKE_CURRENT_LIST_DIR}/abstractstyledialogmodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/abstractstyledialogmodel.h
    ${CMAKE_CURRENT_LIST_DIR}/styleitem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/styleitem.h

    ${CMAKE_CURRENT_LIST_DIR}/notespagemodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/notespagemodel.h
    ${CMAKE_CURRENT_LIST_DIR}/restspagemodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/restspagemodel.h
    ${CMAKE_CURRENT_LIST_DIR}/beamspagemodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/beamspagemodel.h
    ${CMAKE_CURRENT_LIST_DIR}/bendstyleselector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bendstyleselector.h
    ${CMAKE_CURRENT_LIST_DIR}/tieplacementselector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/tieplacementselector.h
    ${CMAKE_CURRENT_LIST_DIR}/accidentalgrouppagemodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/accidentalgrouppagemodel.h
    ${CMAKE_CURRENT_LIST_DIR}/fretboardspagemodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fretboardspagemodel.h
    ${CMAKE_CURRENT_LIST_DIR}/glissandosectionmodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/glissandosectionmodel.h
    ${CMAKE_CURRENT_LIST_DIR}/notelinesectionmodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/notelinesectionmodel.h
    )
