crash:
  - RomanPudashkin
  - DmitryArefiev
  - zacjansheski
engraving:
  - davidstephengrant
VST:
  - RomanPudashkin
"MuseSounds":
  - matthewreadbass
  - sampleeditor
playback:
  - RomanPudashkin
cloud:
  - shoogle
  - Eism