corruption:
    - 'File corruption'
crash:
    - 'Crash or freeze'
engraving:
    - 'Engraving bug'
VST:
    - 'VST bug'
"Muse Sounds":
    - 'Muse Sounds bug'
playback:
    - 'General playback bug'
UI:
    - 'UI bug'
cloud:
    - 'Cloud saving/loading issue'
"needs review":
    - 'Other type of issue'

regression:
    - '(Yes, this used to work in Musescore 3.x and now is broken|Yes, this used to work in a previous version of Musescore 4.x)'

"feature request":
    - 'Problem to be solved'