set P=..\..\..\build.qtc\mtest\libmscore\parts

xcopy /y %P%\part-symbol-del.mscx   	part-symbol-del.mscx
xcopy /y %P%\part-symbol-parts.mscx   	part-symbol-parts.mscx
xcopy /y %P%\part-symbol-uadd.mscx   	part-symbol-uadd.mscx
xcopy /y %P%\part-symbol-udel.mscx   	part-symbol-udel.mscx
xcopy /y %P%\part-symbol-uradd.mscx   	part-symbol-uradd.mscx
xcopy /y %P%\part-symbol-urdel.mscx   	part-symbol-urdel.mscx
xcopy /y %P%\part-all-1.mscx   			part-all.mscx
xcopy /y %P%\part-all-appendmeasures.mscx   part-all-appendmeasures.mscx
xcopy /y %P%\part-all-parts.mscx   			part-all-parts.mscx
xcopy /y %P%\part-all-uappendmeasures.mscx  part-all-uappendmeasures.mscx
xcopy /y %P%\part-all-uinsertmeasures.mscx  part-all-uinsertmeasures.mscx
xcopy /y %P%\part-breath-1.mscx   		part-breath.mscx
xcopy /y %P%\part-breath-add.mscx   	part-breath-add.mscx
xcopy /y %P%\part-breath-del.mscx   	part-breath-del.mscx
xcopy /y %P%\part-breath-parts.mscx   	part-breath-parts.mscx
xcopy /y %P%\part-breath-uadd.mscx   	part-breath-uadd.mscx
xcopy /y %P%\part-breath-udel.mscx   	part-breath-udel.mscx
xcopy /y %P%\part-breath-uradd.mscx  	part-breath-uradd.mscx
xcopy /y %P%\part-breath-urdel.mscx   	part-breath-urdel.mscx
xcopy /y %P%\part-empty-1.mscx   		part-empty.mscx
xcopy /y %P%\part-empty-parts.mscx   	part-empty-parts.mscx
xcopy /y %P%\part-fingering-1.mscx   	part-fingering.mscx
xcopy /y %P%\part-fingering-add.mscx   	part-fingering-add.mscx
xcopy /y %P%\part-fingering-del.mscx   	part-fingering-del.mscx
xcopy /y %P%\part-fingering-parts.mscx  part-fingering-parts.mscx
xcopy /y %P%\part-fingering-uadd.mscx   part-fingering-uadd.mscx
xcopy /y %P%\part-fingering-udel.mscx   part-fingering-udel.mscx
xcopy /y %P%\part-fingering-uradd.mscx  part-fingering-uradd.mscx
xcopy /y %P%\part-fingering-urdel.mscx  part-fingering-urdel.mscx
xcopy /y %P%\partStyle-score-reload-test.mscx   partStyle-score-reload-test.mscx
xcopy /y %P%\partStyle-score-test.mscx   		partStyle-score-test.mscx
xcopy /y %P%\part-symbol-1.mscx   	part-symbol.mscx
xcopy /y %P%\part-symbol-add.mscx   part-symbol-add.mscx


xcopy /y %P%\part1-1.mscx part1.mscx
xcopy /y %P%\part1-2.mscx part1-2o.mscx
xcopy /y %P%\part2-1.mscx part2.mscx
xcopy /y %P%\part2-2.mscx part2-2o.mscx
xcopy /y %P%\part2-4.mscx part2-4o.mscx
xcopy /y %P%\part2-3.mscx part2-3o.mscx
xcopy /y %P%\part2-6.mscx part2-6o.mscx
xcopy /y %P%\part3-1.mscx part3.mscx
xcopy /y %P%\part3-2.mscx part3-2o.mscx
xcopy /y %P%\part4.mscx   part4o.mscx
xcopy /y %P%\part5.mscx   part5o.mscx
xcopy /y %P%\part6.mscx   part6o.mscx
xcopy /y %P%\part7.mscx   part7o.mscx
xcopy /y %P%\part8.mscx   part8o.mscx
xcopy /y %P%\part9.mscx   part9o.mscx
xcopy /y %P%\part10-1.mscx   part10.mscx
xcopy /y %P%\part10-2.mscx   part10-2o.mscx
xcopy /y %P%\part11-1.mscx   part11.mscx
xcopy /y %P%\part11-2.mscx   part11-2o.mscx
xcopy /y %P%\part13.mscx  part13o.mscx
xcopy /y %P%\part14.mscx  part14o.mscx
xcopy /y %P%\part15.mscx  part15o.mscx
xcopy /y %P%\part16.mscx  part16o.mscx
xcopy /y %P%\part17.mscx  part17o.mscx
xcopy /y %P%\part18.mscx  part18o.mscx
xcopy /y %P%\part19.mscx  part19o.mscx
xcopy /y %P%\part20.mscx  part20o.mscx
xcopy /y %P%\part21.mscx  part21o.mscx
xcopy /y %P%\part22.mscx  part22o.mscx
xcopy /y %P%\part23.mscx  part23o.mscx
xcopy /y %P%\part24.mscx  part24o.mscx
