#!/bin/bash

cp ../../../build.debug/mtest/libmscore/parts/part1-1.mscx part1.mscx
cp ../../../build.debug/mtest/libmscore/parts/part1-2.mscx part1-2o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part2-1.mscx part2.mscx
cp ../../../build.debug/mtest/libmscore/parts/part2-2.mscx part2-2o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part2-4.mscx part2-4o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part2-3.mscx part2-3o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part2-6.mscx part2-6o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part3-1.mscx part3.mscx
cp ../../../build.debug/mtest/libmscore/parts/part3-2.mscx part3-2o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part4.mscx   part4o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part5.mscx   part5o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part6.mscx   part6o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part7.mscx   part7o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part8.mscx   part8o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part9.mscx   part9o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part10-1.mscx   part10.mscx
cp ../../../build.debug/mtest/libmscore/parts/part10-2.mscx   part10-2o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part11-1.mscx   part11.mscx
cp ../../../build.debug/mtest/libmscore/parts/part11-2.mscx   part11-2o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part13.mscx  part13o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part14.mscx  part14o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part15.mscx  part15o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part16.mscx  part16o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part17.mscx  part17o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part18.mscx  part18o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part19.mscx  part19o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part20.mscx  part20o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part21.mscx  part21o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part22.mscx  part22o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part23.mscx  part23o.mscx
cp ../../../build.debug/mtest/libmscore/parts/part24.mscx  part24o.mscx
cp ../../../build.debug/mtest/libmscore/parts/partStyle-score-test.mscx partStyle-score-ref.mscx
cp ../../../build.debug/mtest/libmscore/parts/partStyle-score-reload-test.mscx partStyle-score-reload-ref.mscx

# cp ../../../build.debug/mtest/libmscore/parts/part25.mscx  part25o.mscx
# cp ../../../build.debug/mtest/libmscore/parts/part26.mscx  part26o.mscx
# cp ../../../build.debug/mtest/libmscore/parts/part27.mscx  part27o.mscx
# cp ../../../build.debug/mtest/libmscore/parts/part28.mscx  part28o.mscx
# cp ../../../build.debug/mtest/libmscore/parts/part29.mscx  part29o.mscx
# cp ../../../build.debug/mtest/libmscore/parts/part30.mscx  part30o.mscx



