#!/bin/bash

MSCORE=../../build.debug/mtest/importmidi



FILES="m1.mscx
m2.mscx
m3.mscx
m4.mscx
m5.mscx
clef_prev.mscx
clef_melody.mscx
clef_tied.mscx
timesig_changes.mscx
tuplet_off_time_other_bar.mscx
tuplet_off_time_other_bar2.mscx
min_duration.mscx
min_duration_no_reduce.mscx
meter_12-8.mscx
meter_4-4.mscx
meter_9-8.mscx
meter_central_long_note.mscx
meter_central_long_rest.mscx
meter_chord_example.mscx
meter_dots_example1.mscx
meter_dots_example2.mscx
meter_dots_example3.mscx
meter_first_2_8th_rests_compound.mscx
meter_half_rest_3-4.mscx
meter_last_quarter_rest_compound.mscx
meter_rests.mscx
meter_two_beats_over.mscx
perc_drums.mscx
pickup.mscx
quant_dotted_4th.mscx
split_nontuplet.mscx
split_tuplet.mscx
swing_shuffle.mscx
swing_triplets.mscx
tuplet_2_voices_3_5_tuplets.mscx
tuplet_2_voices_tuplet_non.mscx
tuplet_3-4.mscx
tuplet_3_5_7_tuplets.mscx
tuplet_5_5_tuplets_rests.mscx
tuplet_duplet.mscx
tuplet_mars.mscx
tuplet_nonuplet_3-4.mscx
tuplet_nonuplet_4-4.mscx
tuplet_quadruplet.mscx
tuplet_septuplet.mscx
tuplet_tied_3_5_tuplets2.mscx
tuplet_tied_3_5_tuplets.mscx
tuplet_triplet_first_tied2.mscx
tuplet_triplet_first_tied.mscx
tuplet_triplet_last_tied.mscx
tuplet_triplet.mscx
tuplet_triplets_mixed.mscx"

for i in $FILES; do
      cp   $MSCORE/$i .
      done
