#!/bin/bash

if [ "`uname`" = 'Darwin' ]; then
   MSCORE=../../build.xcode/mtest/scripting/Debug
else
   MSCORE=../../build.debug/mtest/scripting
fi

cp $MSCORE/p1.log  p1.log.ref
cp $MSCORE/p2.log  p2.log.ref
cp $MSCORE/testTextStyle-test.mscx  testTextStyle-ref.mscx
cp $MSCORE/testTextStyle-test2.mscx  testTextStyle.mscx

