#!/bin/bash

cp ../../../build.debug/mtest/libmscore/timesig/timesig01.mscx timesig01-ref.mscx
#cp ../../../build.debug/mtest/libmscore/timesig/timesig-02a.mscx timesig-02-ref.mscx
cp ../../../build.debug/mtest/libmscore/timesig/timesig-02.mscx timesig-02-ref.mscx
cp ../../../build.debug/mtest/libmscore/timesig/timesig-03.mscx timesig-03-ref.mscx
cp ../../../build.debug/mtest/libmscore/timesig/timesig-04.mscx timesig-04-ref.mscx

