#!/bin/bash

P=../../../build.debug/mtest/libmscore/compat

cp $P/articulations-test.mscx articulations-ref.mscx
cp $P/keysig-test.mscx keysig-ref.mscx
cp $P/hairpin-test.mscx hairpin-ref.mscx
cp $P/notes-test.mscx notes-ref.mscx
cp $P/textstyles-test.mscx textstyles-ref.mscx
cp $P/title-test.mscx title-ref.mscx

