#!/bin/bash
lupdate instrumentsxml.h  -ts ../locale/instruments_af.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_ar.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_ast.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_be.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_bg.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_ca.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_ca@valencia.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_cs.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_da.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_de.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_el.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_en_GB.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_en_US.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_eo.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_es.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_et.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_eu.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_fa.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_fi.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_fo.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_fr.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_gl.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_he.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_hi_IN.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_hr.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_hu.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_id.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_it.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_ja.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_ka.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_ko.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_lt.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_mn_MN.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_nl.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_nb.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_nn.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_pl.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_pt.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_pt_BR.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_ro.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_ru.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_sk.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_sl.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_sr.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_sv.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_th.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_tr.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_uk.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_uz@Latn.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_vi.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_zh_CN.ts
lupdate instrumentsxml.h  -ts ../locale/instruments_zh_TW.ts