#!/bin/bash

if [ "`uname`" = 'Darwin' ]; then
   S=../../../build.xcode/mtest/libmscore/earlymusic/Debug
else
   S=../../../build.debug/mtest/libmscore/earlymusic
fi

cp $S/mensurstrich01.mscx   mensurstrich01-ref.mscx

