#!/bin/bash

for a in 1; do
      cp ../../../build.debug/mtest/libmscore/tuplet/tuplet${a}.mscx tuplet${a}-ref.mscx
      cp ../../../build.debug/mtest/libmscore/tuplet/split1.mscx split1-ref.mscx
      cp ../../../build.debug/mtest/libmscore/tuplet/split2.mscx split2-ref.mscx
      cp ../../../build.debug/mtest/libmscore/tuplet/split3.mscx split3-ref.mscx
      cp ../../../build.debug/mtest/libmscore/tuplet/split4.mscx split4-ref.mscx
      done

