#!/bin/bash

if [ "`uname`" = 'Darwin' ]; then
   S=../../../build.xcode/mtest/libmscore/tuplet/Debug
else
   S=/home/presario/build-MuseScore-Desktop_Qt_5_9_9_GCC_64bit-Debug/mtest/libmscore/tuplet
fi

cp $S/save-load.mscx save-load.mscx
cp $S/nestedTuplets_addStaff.mscx nestedTuplets_addStaff-ref.mscx

for a in 1; do
      cp $S/tuplet${a}.mscx tuplet${a}-ref.mscx
      cp $S/split1.mscx split1-ref.mscx
      cp $S/split2.mscx split2-ref.mscx
      cp $S/split3.mscx split3-ref.mscx
      cp $S/split4.mscx split4-ref.mscx
      done

