#!/bin/sh

if [ "`uname`" = 'Darwin' ]; then
   S=../../../build.xcode/mtest/libmscore/noregress300old/Debug
else
   S=../../../build.debug/mtest/libmscore/noregress300old
fi

update() {
    for SCORE in $@
    do
        cp -v $S/$SCORE-test-old.mscx $SCORE-ref.mscx
    done
}

update \
    accidentals \
    ambitus \
    articulations \
    breath \
    clefs \
    drumset \
    markers \
    noteheads \
    textstyles \
    tuplets \
    hairpin \
    barlines \
    grace \
    irregular \
    moonlight \

