

set (MIDIIMPORT_SRC
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_beat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_beat.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_chord.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_chord.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_chordname.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_chordname.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_clef.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_clef.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_drum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_drum.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_fraction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_fraction.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_inner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_inner.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_instrument.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_instrument.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_key.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_key.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_lrhand.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_lrhand.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_lyrics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_lyrics.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_meter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_meter.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_model.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_operation.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_operations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_operations.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_quant.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_quant.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_simplify.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_simplify.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_swing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_swing.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tempo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tempo.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tie.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tie.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tuplet.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tuplet_detect.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tuplet_detect.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tuplet_filter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tuplet_filter.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tuplet.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tuplet_tonotes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tuplet_tonotes.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tuplet_voice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_tuplet_voice.h
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_voice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/importmidi_voice.h
    )
