#!/bin/bash

cp ../../../build.debug/mtest/libmscore/splitstaff/splitstaff01.mscx splitstaff01-ref.mscx
cp ../../../build.debug/mtest/libmscore/splitstaff/splitstaff02.mscx splitstaff02-ref.mscx
cp ../../../build.debug/mtest/libmscore/splitstaff/splitstaff03.mscx splitstaff03-ref.mscx
cp ../../../build.debug/mtest/libmscore/splitstaff/splitstaff04.mscx splitstaff04-ref.mscx
cp ../../../build.debug/mtest/libmscore/splitstaff/splitstaff05.mscx splitstaff05-ref.mscx

