/*
 * SPDX-License-Identifier: GPL-3.0-only
 * MuseScore-CLA-applies
 *
 * MuseScore
 * Music Composition & Notation
 *
 * Copyright (C) 2021 MuseScore BVBA and others
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef MU_MPE_SOUNDID_H
#define MU_MPE_SOUNDID_H

#include <unordered_set>

namespace mu::mpe {
enum class SoundId
{
    Undefined = -1,

    Accordion,
    Bandoneon,
    Concertina,
    Harmonica,
    Melodica,
    Sheng,
    Celesta,
    Clavichord,
    Clavinet,
    Harpsichord,
    Virginal,
    Piano,
    Organ,
    Harmonium,
    Synthesizer,
    Theremin,
    OndesMartenot,

    Harp,
    Cavaquinho,
    Guitar,
    BassGuitar,
    Banjo,
    Ukulele,
    Mandolin,
    Mandocello,
    MtnDulcimer,
    Lute,
    Theorbo,
    Archlute,
    Balalaika,
    Bouzouki,
    Koto,
    Oud,
    Shamisen,
    Sitar,
    Prim,
    Brac,
    Bugarija,
    Berda,
    Celo,
    Bandurria,
    Laud,
    Violin,
    ViolinSection,
    Viola,
    ViolaDaGamba,
    ViolaSection,
    Violoncello,
    VioloncelloSection,
    Viol,
    PardessusViol,
    Baryton,
    Violone,
    Nyckelharpa,
    Erhu,
    Contrabass,
    ContrabasseSection,
    Octobass,

    Piccolo,
    Heckelphone,
    HeckelphoneClarinet,
    Oboe,
    Lupophone,
    Flute,
    PanFlute,
    Danso,
    Traverso,
    Dizi,
    Shakuhachi,
    Fife,
    Whistle,
    Flageolet,
    Recorder,
    Ocarina,
    Gemshorn,
    Quena,
    Horn,
    Bassethorn,
    Shawm,
    Cromorne,
    Crumhorn,
    Cornamuse,
    Kelhorn,
    Rauschpfeife,
    Duduk,
    Shenai,
    Clarinet,
    Chalumeau,
    Xaphoon,
    Tarogato,
    Octavin,
    Saxophone,
    Aulochrome,
    Bassoon,
    Contrabassoon,
    Dulcian,
    Rackett,
    Sarrusophone,
    Bagpipe,
    Tuba,
    Cornet,
    Posthorn,
    Trumpet,
    Bugle,
    MellophoneBugle,
    EuphoniumBugle,
    Fiscorn,
    Kuhlohorn,
    Ophicleide,
    Cornettino,
    Cornett,
    Serpent,
    Trombone,
    Cimbasso,
    Sackbut,
    Sousaphone,
    Helicon,
    Conch,
    Horagai,
    Alphorn,
    RagDung,
    Shofar,
    Vuvuzela,

    Timpani,
    RotoToms,
    Tubaphone,
    SteelDrums,
    Glockenspiel,
    Xylophone,
    Xylomarimba,
    Vibraphone,
    Dulcimer,
    Cimbalom,
    Marimba,
    Crotales,
    Almglocken,
    Chimes,
    Carillon,
    Gong,
    Metallophone,
    Flexatone,
    MusicalSaw,
    MusicalGlasses,
    KlaxonHorns,
    Kalimba,
    Bongos,
    Conga,
    Cuica,
    Drumset,
    Drum,
    Tablaa,
    Timbales,
    Anvil,
    Bell,
    Chain,
    Cymbal,
    HiHat,
    Pipe,
    Castanet,
    TamTam,
    Thundersheet,
    Triangle,
    Claves,
    Guiro,
    Block,
    Cabasa,
    Maraca,
    Quijada,
    Ratchet,
    Shaker,
    Stones,
    Tambourine,
    Tubo,
    Vibraslap,
    Whip,
    Snap,
    Clap,
    Slap,
    Stamp,
    Boy,
    Girl,
    Male,
    Female,
    Choir,
    Kazoo
};

enum class SoundCategory
{
    Undefined = -1,
    Keyboards,
    Strings,
    Winds,
    Percussions
};

enum class SoundSubCategory
{
    Undefined = -1,

    Standard,
    English,
    Irish,
    French,
    Chinese,
    Vienna,
    CentralEuropean,

    Baroque,
    Classical,
    Modern,

    Hammond,
    Wagner,
    Orff,
    Huang,
    Hohner,

    Percussive,
    Pipe,
    Rotary,
    Reed,
    Foot,
    Hand,
    Finger,

    Temple,
    Ride,
    Sleigh,
    Cow,
    Marching,

    Splash,
    Crash,
    Plate,
    Bowl,
    Frame,
    Slit,
    Field,
    Snare,
    Brake,
    Slide,
    Pocket,
    Garklein,
    Toy,

    Grand,
    HonkyTonk,
    Upright,
    Prima,
    Secunda,

    Electric,
    Acoustic,
    PedalSteel,
    Metal,
    Iron,
    Brass,
    Tin,
    Nylon,
    Wooden,
    Sandpaper,
    Glass,
    Shell,

    Treble,
    Diatonic,
    Chromatic,
    Octave,

    Alto,
    Tenor,
    Baritone,
    Soprano,
    Mezzo_Soprano,
    Sopranino,
    Counter_Tenor,
    Contra,
    Contra_Alto,
    Sub_Contra_Alto,
    Contra_Bass,
    Double_Contra_Bass,
    Bass,
    Great_Bass,
    Hyper_Bass,

    Tuning_C,
    Tuning_C_sharp,
    Tuning_D,
    Tuning_D_sharp,
    Tuning_E,
    Tuning_F,
    Tuning_F_sharp,
    Tuning_G,
    Tuning_G_sharp,
    Tuning_A,
    Tuning_A_sharp,
    Tuning_B
};

using SoundSubCategories = std::unordered_set<SoundSubCategory>;
}

#endif // MU_MPE_SOUNDID_H
