#!/bin/sh

if [ -z "$test_dir" ]
then
    echo "Error: please set \$test_dir to the folder that contains the test files"
    exit 1
fi

cp $test_dir/accidentals-test.mscx              accidentals-ref.mscx
cp $test_dir/articulations-test.mscx            articulations-ref.mscx
cp $test_dir/chord_symbol-test.mscx             chord_symbol-ref.mscx
cp $test_dir/clef_missing_first-test.mscx       clef_missing_first-ref.mscx
cp $test_dir/clefs-test.mscx                    clefs-ref.mscx
cp $test_dir/drumset-test.mscx                  drumset-ref.mscx
cp $test_dir/fingering-test.mscx                fingering-ref.mscx
cp $test_dir/hairpin-test.mscx                  hairpin-ref.mscx
cp $test_dir/hor_frame_and_mmrest-test.mscx     hor_frame_and_mmrest-ref.mscx
cp $test_dir/keysig-test.mscx                   keysig-ref.mscx
cp $test_dir/markers-test.mscx                  markers-ref.mscx
cp $test_dir/noteheads-test.mscx                noteheads-ref.mscx
cp $test_dir/notes-test.mscx                    notes-ref.mscx
cp $test_dir/notes_useroffset-test.mscx         notes_useroffset-ref.mscx
cp $test_dir/ottava-test.mscx                   ottava-ref.mscx
cp $test_dir/pedal-test.mscx                    pedal-ref.mscx
cp $test_dir/slurs-test.mscx                    slurs-ref.mscx
cp $test_dir/style-test.mscx                    style-ref.mscx
cp $test_dir/tamtam-test.mscx                   tamtam-ref.mscx
cp $test_dir/text_scaling-test.mscx             text_scaling-ref.mscx
cp $test_dir/textline-test.mscx                 textline-ref.mscx
cp $test_dir/textstyles-test.mscx               textstyles-ref.mscx
cp $test_dir/title-test.mscx                    title-ref.mscx
cp $test_dir/tremolo2notes-test.mscx            tremolo2notes-ref.mscx
cp $test_dir/tuplets-test.mscx                  tuplets-ref.mscx
cp $test_dir/tuplets_1-test.mscx                tuplets_1-ref.mscx
cp $test_dir/tuplets_2-test.mscx                tuplets_2-ref.mscx
