/* ============================================== */
/* App                                            */
/* ============================================== */

#define MUSE_APP_NAME_HUMAN_READABLE "MuseScore Studio"
#define MUSE_APP_NAME_MACHINE_READABLE "MuseScoreStudio"

#define MUSE_APP_NAME_HUMAN_READABLE_COMPAT "MuseScore"
#define MUSE_APP_NAME_MACHINE_READABLE_COMPAT "MuseScore"

// TODO: Remove
#define MUSE_APP_NAME "MuseScore"
#define MUSE_APP_TITLE "MuseScore Studio"
// ---

#define MUSE_APP_UNSTABLE 1
/* #undef MUSE_APP_REVISION */
/* #undef MUSE_APP_BUILD_NUMBER */
#define MUSE_APP_VERSION "4.6.0"
#define MUSE_APP_VERSION_MAJOR "4"
#define MUSE_APP_VERSION_MINOR "6"
#define MUSE_APP_VERSION_PATCH "0"

/* #undef MUSE_APP_VERSION_LABEL */

/* #undef MUSE_APP_INSTALL_SUFFIX */
#define MUSE_APP_INSTALL_PREFIX "/usr/local"
#define MUSE_APP_INSTALL_NAME "Contents/Resources/"

/* ============================================== */
/* Modules                                        */
/* ============================================== */

#define MUSE_MODULE_ACCESSIBILITY 1
#define MUSE_MODULE_ACCESSIBILITY_TESTS 1
#define MUSE_MODULE_ACCESSIBILITY_API 1

#define MUSE_MODULE_ACTIONS 1
#define MUSE_MODULE_ACTIONS_TESTS 1
#define MUSE_MODULE_ACTIONS_API 1

#define MUSE_MODULE_AUDIO 1
#define MUSE_MODULE_AUDIO_TESTS 1
#define MUSE_MODULE_AUDIO_API 1
/* #undef MUSE_MODULE_AUDIO_JACK */
#define MUSE_MODULE_AUDIO_EXPORT 1

#define MUSE_MODULE_AUDIOPLUGINS 1

#define MUSE_MODULE_AUTOBOT 1
#define MUSE_MODULE_AUTOBOT_TESTS 1
#define MUSE_MODULE_AUTOBOT_API 1

#define MUSE_MODULE_CLOUD 1
#define MUSE_MODULE_CLOUD_TESTS 1
#define MUSE_MODULE_CLOUD_API 1

#define MUSE_MODULE_DIAGNOSTICS 1
#define MUSE_MODULE_DIAGNOSTICS_TESTS 1
#define MUSE_MODULE_DIAGNOSTICS_API 1
/* #undef MUSE_MODULE_DIAGNOSTICS_CRASHPAD_CLIENT */

#define MUSE_MODULE_DRAW 1
#define MUSE_MODULE_DRAW_TESTS 1
#define MUSE_MODULE_DRAW_API 1
#define MUSE_MODULE_DRAW_USE_QTFONTMETRICS 1

#define MUSE_MODULE_EXTENSIONS 1
#define MUSE_MODULE_EXTENSIONS_TESTS 1
#define MUSE_MODULE_EXTENSIONS_API 1

#define MUSE_MODULE_GLOBAL 1
#define MUSE_MODULE_GLOBAL_TESTS 1
#define MUSE_MODULE_GLOBAL_API 1

#define MUSE_MODULE_LANGUAGES 1
#define MUSE_MODULE_LANGUAGES_TESTS 1
#define MUSE_MODULE_LANGUAGES_API 1

#define MUSE_MODULE_LEARN 1
#define MUSE_MODULE_LEARN_TESTS 1
#define MUSE_MODULE_LEARN_API 1

#define MUSE_MODULE_MIDI 1
#define MUSE_MODULE_MIDI_TESTS 1
#define MUSE_MODULE_MIDI_API 1

#define MUSE_MODULE_MPE 1
#define MUSE_MODULE_MPE_TESTS 1
#define MUSE_MODULE_MPE_API 1

#define MUSE_MODULE_MULTIINSTANCES 1
#define MUSE_MODULE_MULTIINSTANCES_TESTS 1
#define MUSE_MODULE_MULTIINSTANCES_API 1

#define MUSE_MODULE_MUSESAMPLER 1
#define MUSE_MODULE_MUSESAMPLER_TESTS 1
#define MUSE_MODULE_MUSESAMPLER_API 1
/* #undef MUSE_MODULE_MUSESAMPLER_LOAD_IN_DEBUG */

#define MUSE_MODULE_NETWORK 1
#define MUSE_MODULE_NETWORK_TESTS 1
#define MUSE_MODULE_NETWORK_API 1

#define MUSE_MODULE_SHORTCUTS 1
#define MUSE_MODULE_SHORTCUTS_TESTS 1
#define MUSE_MODULE_SHORTCUTS_API 1

#define MUSE_MODULE_TOURS 1
#define MUSE_MODULE_TOURS_TESTS 1
#define MUSE_MODULE_TOURS_API 1

#define MUSE_MODULE_UI 1
#define MUSE_MODULE_UI_TESTS 1
#define MUSE_MODULE_UI_API 1
/* #undef MUSE_MODULE_UI_DISABLE_MODALITY */

#define MUSE_MODULE_UPDATE 1
#define MUSE_MODULE_UPDATE_TESTS 1
#define MUSE_MODULE_UPDATE_API 1

/* #undef MUSE_MODULE_VST */
/* #undef MUSE_MODULE_VST_TESTS */
/* #undef MUSE_MODULE_VST_API */

#define MUSE_MODULE_WORKSPACE 1
#define MUSE_MODULE_WORKSPACE_TESTS 1
#define MUSE_MODULE_WORKSPACE_API 1

#define MUSE_ENABLE_UNIT_TESTS 1

