#!/bin/bash

cp ../../../build.debug/mtest/libmscore/copypastesymbollist/copypastesymbollist-articulation.mscx copypastesymbollist-articulation-ref.mscx
cp ../../../build.debug/mtest/libmscore/copypastesymbollist/copypastesymbollist-chordnames-01.mscx copypastesymbollist-chordnames-01-ref.mscx
cp ../../../build.debug/mtest/libmscore/copypastesymbollist/copypastesymbollist-chordnames.mscx copypastesymbollist-chordnames-ref.mscx
cp ../../../build.debug/mtest/libmscore/copypastesymbollist/copypastesymbollist-figuredbass.mscx copypastesymbollist-figuredbass-ref.mscx
cp ../../../build.debug/mtest/libmscore/copypastesymbollist/copypastesymbollist-lyrics.mscx copypastesymbollist-lyrics-ref.mscx


