<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.40">
  <Style>
    <pageWidth>16.54</pageWidth>
    <pageHeight>11.69</pageHeight>
    <pagePrintableWidth>15.7526</pagePrintableWidth>
    <pageEvenLeftMargin>0.393701</pageEvenLeftMargin>
    <pageOddLeftMargin>0.393701</pageOddLeftMargin>
    <pageEvenTopMargin>0.393701</pageEvenTopMargin>
    <pageEvenBottomMargin>0.393701</pageEvenBottomMargin>
    <pageOddTopMargin>0.393701</pageOddTopMargin>
    <pageOddBottomMargin>0.393701</pageOddBottomMargin>
    <pageTwosided>1</pageTwosided>
    <staffUpperBorder>3</staffUpperBorder>
    <staffLowerBorder>3</staffLowerBorder>
    <lyricsMinBottomDistance>4</lyricsMinBottomDistance>
    <lyricsOddFontFace>Arial</lyricsOddFontFace>
    <lyricsEvenFontFace>Arial</lyricsEvenFontFace>
    <systemFrameDistance>5</systemFrameDistance>
    <frameSystemDistance>5</frameSystemDistance>
    <barWidth>0.26</barWidth>
    <doubleBarDistance>0.46</doubleBarDistance>
    <endBarDistance>0.65</endBarDistance>
    <clefLeftMargin>0.64</clefLeftMargin>
    <clefKeyRightMargin>1.75</clefKeyRightMargin>
    <stemWidth>0.23</stemWidth>
    <barNoteDistance>1.2</barNoteDistance>
    <staffLineWidth>0.18</staffLineWidth>
    <beamWidth>0.55</beamWidth>
    <dotMag>1.2</dotMag>
    <articulationMag>1.2</articulationMag>
    <hairpinLineWidth>0.28</hairpinLineWidth>
    <hairpinFramePadding>0</hairpinFramePadding>
    <hairpinFrameWidth>0</hairpinFrameWidth>
    <pedalLineWidth>0.25</pedalLineWidth>
    <pedalFramePadding>0</pedalFramePadding>
    <pedalFrameWidth>0</pedalFrameWidth>
    <harmonyFretDist>0.5</harmonyFretDist>
    <chordSymbolAFramePadding>0</chordSymbolAFramePadding>
    <chordSymbolAFrameWidth>0</chordSymbolAFrameWidth>
    <fretY>2</fretY>
    <createMultiMeasureRests>1</createMultiMeasureRests>
    <slurEndWidth>0.17</slurEndWidth>
    <slurMidWidth>0.25</slurMidWidth>
    <slurDottedWidth>0.2</slurDottedWidth>
    <minTieLength>1.5</minTieLength>
    <voltaFramePadding>0</voltaFramePadding>
    <voltaFrameWidth>0</voltaFrameWidth>
    <ottava8VBText>&lt;sym&gt;ottavaBassaBa&lt;/sym&gt;</ottava8VBText>
    <ottavaFontSize>12</ottavaFontSize>
    <ottavaFontStyle>2</ottavaFontStyle>
    <ottavaFramePadding>0</ottavaFramePadding>
    <ottavaFrameWidth>0</ottavaFrameWidth>
    <tabClef>29</tabClef>
    <tupletFontFace>Arial</tupletFontFace>
    <tupletFontStyle>1</tupletFontStyle>
    <tupletFramePadding>0</tupletFramePadding>
    <tupletFrameWidth>0</tupletFrameWidth>
    <textLinePosAbove x="0" y="-3.5"/>
    <textLinePosBelow x="0" y="3.5"/>
    <textLineFramePadding>0</textLineFramePadding>
    <textLineFrameWidth>0</textLineFrameWidth>
    <defaultAlign>left,baseline</defaultAlign>
    <defaultFramePadding>0</defaultFramePadding>
    <defaultFrameWidth>0</defaultFrameWidth>
    <defaultFrameRound>25</defaultFrameRound>
    <titleFontFace>Arial</titleFontFace>
    <titleFontSize>45</titleFontSize>
    <titleFontStyle>1</titleFontStyle>
    <titleFramePadding>0</titleFramePadding>
    <titleFrameWidth>0</titleFrameWidth>
    <titleFrameRound>25</titleFrameRound>
    <subTitleFontFace>Arial</subTitleFontFace>
    <subTitleFontSize>34</subTitleFontSize>
    <subTitleOffset x="0" y="17"/>
    <subTitleFramePadding>0</subTitleFramePadding>
    <subTitleFrameWidth>0</subTitleFrameWidth>
    <subTitleFrameRound>25</subTitleFrameRound>
    <composerFontFace>Arial</composerFontFace>
    <composerFontSize>28</composerFontSize>
    <composerFontStyle>1</composerFontStyle>
    <composerFramePadding>0</composerFramePadding>
    <composerFrameWidth>0</composerFrameWidth>
    <composerFrameRound>25</composerFrameRound>
    <lyricistFontFace>Arial</lyricistFontFace>
    <lyricistFontSize>28</lyricistFontSize>
    <lyricistFramePadding>0</lyricistFramePadding>
    <lyricistFrameWidth>0</lyricistFrameWidth>
    <lyricistFrameRound>25</lyricistFrameRound>
    <fingeringFontFace>Arial</fingeringFontFace>
    <fingeringFontSize>12</fingeringFontSize>
    <fingeringFontStyle>1</fingeringFontStyle>
    <fingeringFramePadding>0</fingeringFramePadding>
    <fingeringFrameWidth>0</fingeringFrameWidth>
    <fingeringFrameRound>25</fingeringFrameRound>
    <lhGuitarFingeringFramePadding>0</lhGuitarFingeringFramePadding>
    <lhGuitarFingeringFrameWidth>0</lhGuitarFingeringFrameWidth>
    <lhGuitarFingeringFrameRound>25</lhGuitarFingeringFrameRound>
    <rhGuitarFingeringFramePadding>0</rhGuitarFingeringFramePadding>
    <rhGuitarFingeringFrameWidth>0</rhGuitarFingeringFrameWidth>
    <rhGuitarFingeringFrameRound>25</rhGuitarFingeringFrameRound>
    <stringNumberOffset x="0" y="-2"/>
    <longInstrumentFramePadding>0</longInstrumentFramePadding>
    <longInstrumentFrameWidth>0</longInstrumentFrameWidth>
    <shortInstrumentFramePadding>0</shortInstrumentFramePadding>
    <shortInstrumentFrameWidth>0</shortInstrumentFrameWidth>
    <partInstrumentFramePadding>0</partInstrumentFramePadding>
    <partInstrumentFrameWidth>0</partInstrumentFrameWidth>
    <partInstrumentFrameRound>25</partInstrumentFrameRound>
    <dynamicsFontFace>Arial</dynamicsFontFace>
    <dynamicsFontStyle>1</dynamicsFontStyle>
    <dynamicsFramePadding>0</dynamicsFramePadding>
    <dynamicsFrameWidth>0</dynamicsFrameWidth>
    <expressionFontSize>12</expressionFontSize>
    <expressionFramePadding>0</expressionFramePadding>
    <expressionFrameWidth>0</expressionFrameWidth>
    <tempoFramePadding>0</tempoFramePadding>
    <tempoFrameWidth>0</tempoFrameWidth>
    <tempoFrameRound>25</tempoFrameRound>
    <metronomeFramePadding>0</metronomeFramePadding>
    <metronomeFrameWidth>0</metronomeFrameWidth>
    <measureNumberFontFace>Arial</measureNumberFontFace>
    <measureNumberFontSize>11</measureNumberFontSize>
    <measureNumberFontStyle>1</measureNumberFontStyle>
    <measureNumberPosAbove x="2" y="-2"/>
    <measureNumberAlign>center,bottom</measureNumberAlign>
    <measureNumberFramePadding>0.5</measureNumberFramePadding>
    <measureNumberFrameWidth>0.2</measureNumberFrameWidth>
    <translatorAlign>center,top</translatorAlign>
    <translatorFramePadding>0</translatorFramePadding>
    <translatorFrameWidth>0</translatorFrameWidth>
    <systemTextFontFace>Arial</systemTextFontFace>
    <systemTextFontSize>12</systemTextFontSize>
    <systemTextAlign>left,top</systemTextAlign>
    <systemTextFramePadding>0</systemTextFramePadding>
    <systemTextFrameWidth>0</systemTextFrameWidth>
    <systemTextFrameRound>25</systemTextFrameRound>
    <staffTextFontFace>Arial</staffTextFontFace>
    <staffTextFontSize>12</staffTextFontSize>
    <staffTextFontStyle>1</staffTextFontStyle>
    <staffTextAlign>left,top</staffTextAlign>
    <staffTextPosAbove x="0" y="-4"/>
    <staffTextFramePadding>0</staffTextFramePadding>
    <staffTextFrameWidth>0</staffTextFrameWidth>
    <staffTextFrameRound>25</staffTextFrameRound>
    <repeatLeftFramePadding>0</repeatLeftFramePadding>
    <repeatLeftFrameWidth>0</repeatLeftFrameWidth>
    <repeatLeftFrameRound>25</repeatLeftFrameRound>
    <repeatRightFramePadding>0</repeatRightFramePadding>
    <repeatRightFrameWidth>0</repeatRightFrameWidth>
    <repeatRightFrameRound>25</repeatRightFrameRound>
    <frameFramePadding>0</frameFramePadding>
    <frameFrameWidth>0</frameFrameWidth>
    <glissandoAlign>center,baseline</glissandoAlign>
    <glissandoFramePadding>0</glissandoFramePadding>
    <glissandoFrameWidth>0</glissandoFrameWidth>
    <bendAlign>center,bottom</bendAlign>
    <bendFramePadding>0</bendFramePadding>
    <bendFrameWidth>0</bendFrameWidth>
    <headerFramePadding>0</headerFramePadding>
    <headerFrameWidth>0</headerFrameWidth>
    <footerFontFace>Arial</footerFontFace>
    <footerFontSize>14</footerFontSize>
    <footerOffset x="0" y="-3"/>
    <footerFramePadding>0</footerFramePadding>
    <footerFrameWidth>0</footerFrameWidth>
    <instrumentChangeAlign>left,bottom</instrumentChangeAlign>
    <instrumentChangeFramePadding>0</instrumentChangeFramePadding>
    <instrumentChangeFrameWidth>0</instrumentChangeFrameWidth>
    <user1Name>Repeat Text</user1Name>
    <user1FontSize>12</user1FontSize>
    <user1Align>right,baseline</user1Align>
    <user1FramePadding>0</user1FramePadding>
    <user1FrameWidth>0</user1FrameWidth>
    <letRingPosAbove x="0" y="-4"/>
    <letRingPosBelow x="0" y="4"/>
    <Spatium>6.25</Spatium>
    </Style>
  </museScore>
