#!/bin/bash

if [ "`uname`" = 'Darwin' ]; then
   S=../../../build.xcode/mtest/musicxml/io/Debug
else
   S=../../../build.debug/mtest/musicxml/io
fi

cp $S/testBreaksPage.xml testBreaksPage_no_ref.xml
cp $S/testBreaksPage.xml testBreaksPage_all_ref.xml
cp $S/testBreaksPage.xml testBreaksPage_manual_ref.xml
cp $S/testInstrumentChangeMIDIportExport.xml testInstrumentChangeMIDIportExport_ref.xml
cp $S/testMeasureStyleSlash.mscx testMeasureStyleSlash_ref.mscx
cp $S/testTboxAboveBelow1.xml testTboxAboveBelow1_ref.xml
cp $S/testTboxAboveBelow2.xml testTboxAboveBelow2_ref.xml
cp $S/testTboxAboveBelow3.xml testTboxAboveBelow3_ref.xml
cp $S/testTboxMultiPage1.xml testTboxMultiPage1_ref.xml
cp $S/testTboxVbox1.xml testTboxVbox1_ref.xml
cp $S/testTboxWords1.xml testTboxWords1_ref.xml
cp $S/testBreaksManual.xml testBreaksManual_no_ref.xml
cp $S/testBreaksManual.xml testBreaksManual_manual_ref.xml
cp $S/testBreaksManual.xml testBreaksManual_all_ref.xml
cp $S/testHairpinDynamics.xml testHairpinDynamics_ref.xml
cp $S/testBarStyles2.xml testBarStyles2.xml
cp $S/testSystemBrackets3.xml testSystemBrackets3_ref.xml
cp $S/testTablature1.xml testTablature1.xml
cp $S/testTablature2.xml testTablature2.xml
cp $S/testTablature3.xml testTablature3.xml
cp $S/testTablature4.xml testTablature4.xml
cp $S/testTablature5.xml testTablature5_ref.xml
cp $S/testBeams3.xml testBeams3_ref.xml
cp $S/testTempoPrecision.xml testTempoPrecision_ref.xml
