#!/bin/sh

if [ "`uname`" = 'Darwin' ]; then
   S=../../../build.xcode/mtest/libmscore/compat114/Debug
else
   S=/home/presario/build-MuseScore-Desktop_Qt_5_9_9_GCC_64bit-Debug/mtest/libmscore/compat114
fi

cp $S/accidentals-test.mscx              accidentals-ref.mscx
cp $S/articulations-test.mscx            articulations-ref.mscx
cp $S/chord_symbol-test.mscx             chord_symbol-ref.mscx
cp $S/clef_missing_first-test.mscx       clef_missing_first-ref.mscx
cp $S/clefs-test.mscx                    clefs-ref.mscx
cp $S/hairpin-test.mscx                  hairpin-ref.mscx
cp $S/hor_frame_and_mmrest-test.mscx     hor_frame_and_mmrest-ref.mscx
cp $S/keysig-test.mscx                   keysig-ref.mscx
cp $S/noteheads-test.mscx                noteheads-ref.mscx
cp $S/notes-test.mscx                    notes-ref.mscx
cp $S/slurs-test.mscx                    slurs-ref.mscx
cp $S/style-test.mscx                    style-ref.mscx
cp $S/text_scaling-test.mscx             text_scaling-ref.mscx
cp $S/textstyles-test.mscx               textstyles-ref.mscx
cp $S/title-test.mscx                    title-ref.mscx
cp $S/tremolo2notes-test.mscx            tremolo2notes-ref.mscx
#cp $S/markers-test.mscx                  markers-ref.mscx
cp $S/drumset-test.mscx                  drumset-ref.mscx
cp $S/tuplets-test.mscx                  tuplets-ref.mscx
cp $S/tuplets_1-test.mscx                tuplets_1-ref.mscx
cp $S/tuplets_2-test.mscx                tuplets_2-ref.mscx
cp $S/fingering-test.mscx                fingering-ref.mscx
cp $S/ottava-test.mscx                   ottava-ref.mscx
cp $S/pedal-test.mscx                    pedal-ref.mscx
cp $S/textline-test.mscx                 textline-ref.mscx
cp $S/tamtam-test.mscx                   tamtam-ref.mscx
