#!/bin/bash

MSCORE=../../build.debug/mtest/guitarpro

cp   $MSCORE/testIrrTuplet.gp4.mscx testIrrTuplet.gp4-ref.mscx
cp   $MSCORE/slur.gp4.mscx slur.gp4-ref.mscx
cp   $MSCORE/sforzato.gp4.mscx sforzato.gp4-ref.mscx
cp   $MSCORE/heavy-accent.gp5.mscx heavy-accent.gp5-ref.mscx
cp   $MSCORE/tremolos.gp5.mscx tremolos.gp5-ref.mscx
cp   $MSCORE/trill.gp4.mscx trill.gp4-ref.mscx
cp   $MSCORE/dynamic.gp5.mscx dynamic.gp5-ref.mscx
cp   $MSCORE/arpeggio_up_down.gp4.mscx arpeggio_up_down.gp4-ref.mscx
cp   $MSCORE/ghost_note.gp3.mscx ghost_note.gp3-ref.mscx
cp   $MSCORE/grace.gp5.mscx grace.gp5-ref.mscx
cp   $MSCORE/volta.gp5.mscx volta.gp5-ref.mscx
cp   $MSCORE/volta.gp4.mscx volta.gp4-ref.mscx
cp   $MSCORE/volta.gp3.mscx volta.gp3-ref.mscx
cp   $MSCORE/copyright.gp5.mscx copyright.gp5-ref.mscx
cp   $MSCORE/copyright.gp4.mscx copyright.gp4-ref.mscx
cp   $MSCORE/copyright.gp3.mscx copyright.gp3-ref.mscx
cp   $MSCORE/tempo.gp5.mscx tempo.gp5-ref.mscx
cp   $MSCORE/tempo.gp4.mscx tempo.gp4-ref.mscx
cp   $MSCORE/tempo.gp3.mscx tempo.gp3-ref.mscx
cp   $MSCORE/basic-bend.gp5.mscx basic-bend.gp5-ref.mscx
cp   $MSCORE/bend.gp5.mscx bend.gp5-ref.mscx
cp   $MSCORE/bend.gp4.mscx bend.gp4-ref.mscx
cp   $MSCORE/bend.gp3.mscx bend.gp3-ref.mscx
cp   $MSCORE/keysig.gp5.mscx keysig.gp5-ref.mscx
cp   $MSCORE/keysig.gp4.mscx keysig.gp4-ref.mscx
cp   $MSCORE/dotted-tuplets.gp5.mscx dotted-tuplets.gp5-ref.mscx
cp   $MSCORE/tuplet-with-slur.gp4.mscx tuplet-with-slur.gp4-ref.mscx
cp   $MSCORE/beams-stems-ledger-lines.gp5.mscx beams-stems-ledger-lines.gp5-ref.mscx
cp   $MSCORE/fret-diagram.gpx.mscx fret-diagram.gpx-ref.mscx
cp   $MSCORE/fret-diagram.gp5.mscx fret-diagram.gp5-ref.mscx
cp   $MSCORE/fret-diagram.gp4.mscx fret-diagram.gp4-ref.mscx

