init init/oneStaffWithNotesAndMM.mscx
cmd first-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd next-element
cmd toggle-visible
cmd next-element
inspector BarLine offset 0;-12.5
inspector BarLine offset 0;-25
test score 301436-navigate-mmrest.mscx
