init init/Treble.mscx
cmd note-input
cmd note-c
cmd next-measure
palette MeasureRepeat subtype 1
cmd next-measure
cmd note-d
cmd next-measure
cmd note-e
cmd next-measure
palette MeasureRepeat subtype 2
cmd next-measure
cmd next-measure
cmd note-f
cmd next-measure
cmd note-e
cmd next-measure
cmd note-d
cmd next-measure
cmd note-c
cmd next-measure
palette MeasureRepeat subtype 4
test score measure-repeat-add.mscx
