init init/Treble.mscx
cmd note-input
cmd escape
cmd next-chord
cmd next-chord
palette KeySig accidental -7
cmd prev-chord
palette KeySig accidental 7
cmd next-chord
cmd next-chord
cmd next-chord
palette KeySig accidental 4
cmd next-chord
cmd next-chord
palette KeySig accidental 0
cmd next-chord
cmd next-chord
palette KeySig accidental 2
cmd prev-chord
cmd prev-chord
cmd prev-chord
palette KeySig accidental -2
test score palette_keysigs_3.mscx
