#!/bin/bash

for a in Beam-23.mscx Beam-2.mscx Beam-A.mscx Beam-B.mscx Beam-C.mscx \
   Beam-dir.mscx Beam-D.mscx Beam-E.mscx Beam-F.mscx Beam-G.mscx \
   Beam-S0.mscx Beam-CrossM2.mscx Beam-CrossM3.mscx \
   Beam-CrossM4.mscx; do
      cp ../../../build.debug/mtest/libmscore/beam/$a .
      done


