#!/bin/bash

if [ "`uname`" = 'Darwin' ]; then
   S=../../../build.xcode/mtest/libmscore/tools/Debug
else
   S=../../../build.debug/mtest/libmscore/tools
fi

for a in undoAddLineBreaks \
   undoExplode undoImplode undoImplodeVoice undoSlashFill \
   undoSlashRhythm undoResequenceAlpha undoResequenceNumeric \
   undoChangeVoice undoResequencePart undoSlashFill undoSlashRhythm \
   undoResequenceMeasure; do
      echo ${a}
      cp $S/${a}01-test.mscx ${a}01-ref.mscx
      cp $S/${a}02-test.mscx ${a}02-ref.mscx
      done
