set P=..\..\..\build.debug\mtest\libmscore\link

xcopy /y %P%\part1-1.mscx part1.mscx
xcopy /y %P%\part1-2.mscx part1-2o.mscx
xcopy /y %P%\part2-1.mscx part2.mscx
xcopy /y %P%\part2-2.mscx part2-2o.mscx
xcopy /y %P%\part2-4.mscx part2-4o.mscx
xcopy /y %P%\part2-3.mscx part2-3o.mscx
xcopy /y %P%\part2-6.mscx part2-6o.mscx
xcopy /y %P%\part3-1.mscx part3.mscx
xcopy /y %P%\part3-2.mscx part3-2o.mscx
xcopy /y %P%\part4.mscx   part4o.mscx
xcopy /y %P%\part5.mscx   part5o.mscx
xcopy /y %P%\part6.mscx   part6o.mscx
xcopy /y %P%\part7.mscx   part7o.mscx
xcopy /y %P%\part8.mscx   part8o.mscx
xcopy /y %P%\part9.mscx   part9o.mscx
xcopy /y %P%\part10-1.mscx   part10.mscx
xcopy /y %P%\part10-2.mscx   part10-2o.mscx
xcopy /y %P%\part11-1.mscx   part11.mscx
xcopy /y %P%\part11-2.mscx   part11-2o.mscx
xcopy /y %P%\part13.mscx  part13o.mscx
xcopy /y %P%\part14.mscx  part14o.mscx
xcopy /y %P%\part15.mscx  part15o.mscx
xcopy /y %P%\part16.mscx  part16o.mscx
xcopy /y %P%\part17.mscx  part17o.mscx
xcopy /y %P%\part18.mscx  part18o.mscx
xcopy /y %P%\part19.mscx  part19o.mscx
xcopy /y %P%\part20.mscx  part20o.mscx
xcopy /y %P%\part21.mscx  part21o.mscx
xcopy /y %P%\part22.mscx  part22o.mscx
xcopy /y %P%\part23.mscx  part23o.mscx
xcopy /y %P%\part24.mscx  part24o.mscx