#!/bin/sh

if [ "`uname`" = 'Darwin' ]; then
   S=../../../build.xcode/mtest/libmscore/compat206/Debug
else
   S=../../../build.debug/mtest/libmscore/compat206
fi

cp $S/accidentals-test.mscx accidentals-ref.mscx
cp $S/articulations-test.mscx articulations-ref.mscx
cp $S/breath-test.mscx breath-ref.mscx
cp $S/clefs-test.mscx clefs-ref.mscx
cp $S/markers-test.mscx markers-ref.mscx
cp $S/textstyles-test.mscx textstyles-ref.mscx
