/*
 * SPDX-License-Identifier: GPL-3.0-only
 * MuseScore-CLA-applies
 *
 * MuseScore
 * Music Composition & Notation
 *
 * Copyright (C) 2021 MuseScore Limited and others
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
#include "utils.h"

#include "translation.h"

using namespace muse;

static constexpr const char* noteNamesWithOctaves[] = {
    QT_TRANSLATE_NOOP("EditPitchBase", "C -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♯ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♯ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♭ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♯ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♭ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♯ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♭ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♯ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♭ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♯ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♭ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♯ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♭ -1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♯ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♭ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♯ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♭ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♯ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♭ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♯ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♭ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♯ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♭ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♯ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♭ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♯ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♭ 0"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♯ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♭ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♯ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♭ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♯ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♭ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♯ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♭ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♯ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♭ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♯ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♭ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♯ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♭ 1"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♯ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♭ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♯ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♭ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♯ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♭ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♯ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♭ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♯ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♭ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♯ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♭ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♯ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♭ 2"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♯ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♭ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♯ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♭ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♯ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♭ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♯ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♭ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♯ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♭ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♯ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♭ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♯ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♭ 3"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♯ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♭ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♯ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♭ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♯ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♭ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♯ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♭ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♯ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♭ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♯ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♭ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♯ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♭ 4"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♯ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♭ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♯ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♭ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♯ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♭ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♯ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♭ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♯ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♭ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♯ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♭ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♯ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♭ 5"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♯ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♭ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♯ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♭ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♯ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♭ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♯ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♭ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♯ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♭ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♯ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♭ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♯ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♭ 6"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♯ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♭ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♯ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♭ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♯ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♭ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♯ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♭ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♯ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♭ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♯ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♭ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♯ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♭ 7"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♯ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♭ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♯ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♭ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♯ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♭ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♯ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♭ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♯ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♭ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♯ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "A♭ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♯ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "B♭ 8"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♯ 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "C♭ 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♯ 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "D♭ 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♯ 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "E♭ 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♯ 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "F♭ 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G 9"),
    QT_TRANSLATE_NOOP("EditPitchBase", "G♭ 9"),
};

static constexpr const char* sharpNotes[] = {
    QT_TRANSLATE_NOOP("global", "C"),
    QT_TRANSLATE_NOOP("global", "C♯"),
    QT_TRANSLATE_NOOP("global", "D"),
    QT_TRANSLATE_NOOP("global", "D♯"),
    QT_TRANSLATE_NOOP("global", "E"),
    QT_TRANSLATE_NOOP("global", "F"),
    QT_TRANSLATE_NOOP("global", "F♯"),
    QT_TRANSLATE_NOOP("global", "G"),
    QT_TRANSLATE_NOOP("global", "G♯"),
    QT_TRANSLATE_NOOP("global", "A"),
    QT_TRANSLATE_NOOP("global", "A♯"),
    QT_TRANSLATE_NOOP("global", "B")
};

static constexpr const char* flatNotes[] = {
    QT_TRANSLATE_NOOP("global", "C"),
    QT_TRANSLATE_NOOP("global", "D♭"),
    QT_TRANSLATE_NOOP("global", "D"),
    QT_TRANSLATE_NOOP("global", "E♭"),
    QT_TRANSLATE_NOOP("global", "E"),
    QT_TRANSLATE_NOOP("global", "F"),
    QT_TRANSLATE_NOOP("global", "G♭"),
    QT_TRANSLATE_NOOP("global", "G"),
    QT_TRANSLATE_NOOP("global", "A♭"),
    QT_TRANSLATE_NOOP("global", "A"),
    QT_TRANSLATE_NOOP("global", "B♭"),
    QT_TRANSLATE_NOOP("global", "B")
};

std::string muse::pitchToString(int pitch, bool addoctave, bool useFlats /* = false */)
{
    if (pitch < 0 || pitch > 127) {
        return std::string();
    }

    auto source = useFlats ? flatNotes : sharpNotes;

    int i = pitch % 12;
    if (addoctave) {
        int octave = (pitch / 12) - 1;
        std::string key = std::string(source[i]) + " " + std::to_string(octave);
        return muse::trc("EditPitchBase", key.c_str());
    }
    return muse::trc("global", source[i]);
}
