#!/bin/bash

if [ -z "$test_dir" ]
then
    echo "Error: please set \$test_dir to the folder that contains the test files"
    exit 1
fi

cp $test_dir/voices.mscx voices-ref.mscx

cp $test_dir/part-all-appendmeasures.mscx      part-all-appendmeasures.mscx
cp $test_dir/part-all-uappendmeasures.mscx     part-all-uappendmeasures.mscx

cp $test_dir/part-all-insertmeasures.mscx      part-all-insertmeasures.mscx
cp $test_dir/part-all-uinsertmeasures.mscx     part-all-uinsertmeasures.mscx

cp $test_dir/partStyle-score-test.mscx         partStyle-score-ref.mscx
cp $test_dir/partStyle-score-reload-test.mscx  partStyle-score-reload-ref.mscx

#cp $test_dir/partStyle-part-default-test.mscx  partStyle-part-default-ref.mscx
#cp $test_dir/partStyle-score-default-test.mscx partStyle-score-default-ref.mscx

cp $test_dir/part-empty-1.mscx     part-empty.mscx
cp $test_dir/part-empty-parts.mscx part-empty-parts.mscx

cp $test_dir/part-all-1.mscx     part-all.mscx
cp $test_dir/part-all-parts.mscx part-all-parts.mscx

cp $test_dir/part-54346-1.mscx     part-54346.mscx
cp $test_dir/part-54346-parts.mscx part-54346-parts.mscx

cp $test_dir/part-breath-1.mscx     part-breath.mscx
cp $test_dir/part-breath-parts.mscx part-breath-parts.mscx
cp $test_dir/part-breath-add.mscx   part-breath-add.mscx
cp $test_dir/part-breath-uadd.mscx  part-breath-uadd.mscx
cp $test_dir/part-breath-uradd.mscx part-breath-uradd.mscx
cp $test_dir/part-breath-del.mscx   part-breath-del.mscx
cp $test_dir/part-breath-udel.mscx  part-breath-udel.mscx
cp $test_dir/part-breath-urdel.mscx part-breath-urdel.mscx

cp $test_dir/part-fingering-1.mscx     part-fingering.mscx
cp $test_dir/part-fingering-parts.mscx part-fingering-parts.mscx
cp $test_dir/part-fingering-add.mscx   part-fingering-add.mscx
cp $test_dir/part-fingering-uadd.mscx  part-fingering-uadd.mscx
cp $test_dir/part-fingering-uradd.mscx part-fingering-uradd.mscx
cp $test_dir/part-fingering-del.mscx   part-fingering-del.mscx
cp $test_dir/part-fingering-udel.mscx  part-fingering-udel.mscx
cp $test_dir/part-fingering-urdel.mscx part-fingering-urdel.mscx

cp $test_dir/part-symbol-1.mscx     part-symbol.mscx
cp $test_dir/part-symbol-parts.mscx part-symbol-parts.mscx
cp $test_dir/part-symbol-add.mscx   part-symbol-add.mscx
cp $test_dir/part-symbol-uadd.mscx  part-symbol-uadd.mscx
cp $test_dir/part-symbol-uradd.mscx part-symbol-uradd.mscx
cp $test_dir/part-symbol-del.mscx   part-symbol-del.mscx
cp $test_dir/part-symbol-udel.mscx  part-symbol-udel.mscx
cp $test_dir/part-symbol-urdel.mscx part-symbol-urdel.mscx

cp $test_dir/part-chordline-1.mscx     part-chordline.mscx
cp $test_dir/part-chordline-parts.mscx part-chordline-parts.mscx
cp $test_dir/part-chordline-add.mscx   part-chordline-add.mscx
cp $test_dir/part-chordline-uadd.mscx  part-chordline-uadd.mscx
cp $test_dir/part-chordline-uradd.mscx part-chordline-uradd.mscx
cp $test_dir/part-chordline-del.mscx   part-chordline-del.mscx
cp $test_dir/part-chordline-udel.mscx  part-chordline-udel.mscx
cp $test_dir/part-chordline-urdel.mscx part-chordline-urdel.mscx

cp $test_dir/part-measure-repeat-1.mscx     part-measure-repeat.mscx
cp $test_dir/part-measure-repeat-parts.mscx part-measure-repeat-parts.mscx
cp $test_dir/part-measure-repeat-add.mscx   part-measure-repeat-add.mscx
cp $test_dir/part-measure-repeat-uadd.mscx  part-measure-repeat-uadd.mscx
cp $test_dir/part-measure-repeat-uradd.mscx part-measure-repeat-uradd.mscx
cp $test_dir/part-measure-repeat-del.mscx   part-measure-repeat-del.mscx
cp $test_dir/part-measure-repeat-udel.mscx  part-measure-repeat-udel.mscx
cp $test_dir/part-measure-repeat-urdel.mscx part-measure-repeat-urdel.mscx

cp $test_dir/part-image-1.mscx     part-image.mscx
cp $test_dir/part-image-parts.mscx part-image-parts.mscx
cp $test_dir/part-image-add.mscx   part-image-add.mscx
cp $test_dir/part-image-uadd.mscx  part-image-uadd.mscx
cp $test_dir/part-image-uradd.mscx part-image-uradd.mscx
cp $test_dir/part-image-del.mscx   part-image-del.mscx
cp $test_dir/part-image-udel.mscx  part-image-udel.mscx
cp $test_dir/part-image-urdel.mscx part-image-urdel.mscx

cp $test_dir/part-stemless-1.mscx     part-stemless.mscx
cp $test_dir/part-stemless-parts.mscx part-stemless-parts.mscx
