set P=..\..\..\build.qtc\mtest\libmscore\parts

xcopy /y %P%\part-symbol-1.mscx   	part-symbol.mscx
xcopy /y %P%\part-symbol-add.mscx   part-symbol-add.mscx
xcopy /y %P%\part-symbol-del.mscx   	part-symbol-del.mscx
xcopy /y %P%\part-symbol-parts.mscx   	part-symbol-parts.mscx
xcopy /y %P%\part-symbol-uadd.mscx   	part-symbol-uadd.mscx
xcopy /y %P%\part-symbol-udel.mscx   	part-symbol-udel.mscx
xcopy /y %P%\part-symbol-uradd.mscx   	part-symbol-uradd.mscx
xcopy /y %P%\part-symbol-urdel.mscx   	part-symbol-urdel.mscx
xcopy /y %P%\part-all-1.mscx   			part-all.mscx
xcopy /y %P%\part-all-appendmeasures.mscx   part-all-appendmeasures.mscx
xcopy /y %P%\part-all-parts.mscx   			part-all-parts.mscx
xcopy /y %P%\part-all-uappendmeasures.mscx  part-all-uappendmeasures.mscx
xcopy /y %P%\part-all-uinsertmeasures.mscx  part-all-uinsertmeasures.mscx
xcopy /y %P%\part-breath-1.mscx   		part-breath.mscx
xcopy /y %P%\part-breath-add.mscx   	part-breath-add.mscx
xcopy /y %P%\part-breath-del.mscx   	part-breath-del.mscx
xcopy /y %P%\part-breath-parts.mscx   	part-breath-parts.mscx
xcopy /y %P%\part-breath-uadd.mscx   	part-breath-uadd.mscx
xcopy /y %P%\part-breath-udel.mscx   	part-breath-udel.mscx
xcopy /y %P%\part-breath-uradd.mscx  	part-breath-uradd.mscx
xcopy /y %P%\part-breath-urdel.mscx   	part-breath-urdel.mscx
xcopy /y %P%\part-empty-1.mscx   		part-empty.mscx
xcopy /y %P%\part-empty-parts.mscx   	part-empty-parts.mscx
xcopy /y %P%\part-fingering-1.mscx   	part-fingering.mscx
xcopy /y %P%\part-fingering-add.mscx   	part-fingering-add.mscx
xcopy /y %P%\part-fingering-del.mscx   	part-fingering-del.mscx
xcopy /y %P%\part-fingering-parts.mscx  part-fingering-parts.mscx
xcopy /y %P%\part-fingering-uadd.mscx   part-fingering-uadd.mscx
xcopy /y %P%\part-fingering-udel.mscx   part-fingering-udel.mscx
xcopy /y %P%\part-fingering-uradd.mscx  part-fingering-uradd.mscx
xcopy /y %P%\part-fingering-urdel.mscx  part-fingering-urdel.mscx
xcopy /y %P%\partStyle-score-reload-test.mscx   partStyle-score-reload-test.mscx
xcopy /y %P%\partStyle-score-test.mscx   		partStyle-score-test.mscx

xcopy /y %P%\part-chordline-1.mscx     part-chordline.mscx
xcopy /y %P%\part-chordline-add.mscx   part-chordline-add.mscx
xcopy /y %P%\part-chordline-del.mscx   part-chordline-del.mscx
xcopy /y %P%\part-chordline-parts.mscx part-chordline-parts.mscx
xcopy /y %P%\part-chordline-uadd.mscx  part-chordline-uadd.mscx
xcopy /y %P%\part-chordline-udel.mscx  part-chordline-udel.mscx
xcopy /y %P%\part-chordline-uradd.mscx part-chordline-uradd.mscx
xcopy /y %P%\part-chordline-urdel.mscx part-chordline-urdel.mscx