#!/bin/bash

cp ../../../build.debug/mtest/libmscore/split/split6.mscx split6-ref.mscx
cp ../../../build.debug/mtest/libmscore/split/split5.mscx split5-ref.mscx
cp ../../../build.debug/mtest/libmscore/split/split4.mscx split4-ref.mscx
cp ../../../build.debug/mtest/libmscore/split/split3.mscx split3-ref.mscx
cp ../../../build.debug/mtest/libmscore/split/split2.mscx split2-ref.mscx
cp ../../../build.debug/mtest/libmscore/split/split1.mscx split1-ref.mscx
cp ../../../build.debug/mtest/libmscore/split/split.mscx split-ref.mscx

