<?xml version="1.0" encoding="UTF-8"?>
<museScore version="2.04">
  <Style>
    <staffUpperBorder>6</staffUpperBorder>
    <staffLowerBorder>4</staffLowerBorder>
    <staffDistance>6.5</staffDistance>
    <akkoladeDistance>6.5</akkoladeDistance>
    <minSystemDistance>9</minSystemDistance>
    <maxSystemDistance>15</maxSystemDistance>
    <lyricsDistance>2</lyricsDistance>
    <lyricsMinBottomDistance>4</lyricsMinBottomDistance>
    <lyricsLineHeight>1</lyricsLineHeight>
    <figuredBassFontFamily>MScoreBC</figuredBassFontFamily>
    <figuredBassFontSize>8</figuredBassFontSize>
    <figuredBassYOffset>6</figuredBassYOffset>
    <figuredBassLineHeight>1</figuredBassLineHeight>
    <figuredBassAlignment>0</figuredBassAlignment>
    <figuredBassStyle>0</figuredBassStyle>
    <systemFrameDistance>7</systemFrameDistance>
    <frameSystemDistance>7</frameSystemDistance>
    <minMeasureWidth>5</minMeasureWidth>
    <barWidth>0.16</barWidth>
    <doubleBarWidth>0.16</doubleBarWidth>
    <endBarWidth>0.5</endBarWidth>
    <doubleBarDistance>0.3</doubleBarDistance>
    <endBarDistance>0.4</endBarDistance>
    <repeatBarTips>1</repeatBarTips>
    <startBarlineSingle>0</startBarlineSingle>
    <startBarlineMultiple>1</startBarlineMultiple>
    <bracketWidth>0.45</bracketWidth>
    <bracketDistance>0.1</bracketDistance>
    <akkoladeWidth>1.6</akkoladeWidth>
    <akkoladeBarDistance>0.4</akkoladeBarDistance>
    <clefLeftMargin>0.64</clefLeftMargin>
    <keysigLeftMargin>0.5</keysigLeftMargin>
    <timesigLeftMargin>0.5</timesigLeftMargin>
    <clefKeyRightMargin>1.75</clefKeyRightMargin>
    <clefBarlineDistance>0.18</clefBarlineDistance>
    <stemWidth>0.16</stemWidth>
    <shortenStem>1</shortenStem>
    <shortStemProgression>0.25</shortStemProgression>
    <shortestStem>2.25</shortestStem>
    <beginRepeatLeftMargin>1</beginRepeatLeftMargin>
    <minNoteDistance>0.25</minNoteDistance>
    <barNoteDistance>1.2</barNoteDistance>
    <barAccidentalDistance>0.3</barAccidentalDistance>
    <multiMeasureRestMargin>1.2</multiMeasureRestMargin>
    <noteBarDistance>1</noteBarDistance>
    <measureSpacing>1.2</measureSpacing>
    <staffLineWidth>0.08</staffLineWidth>
    <ledgerLineWidth>0.16</ledgerLineWidth>
    <ledgerLineLength>0.6</ledgerLineLength>
    <accidentalDistance>0.22</accidentalDistance>
    <accidentalNoteDistance>0.22</accidentalNoteDistance>
    <beamWidth>0.5</beamWidth>
    <beamDistance>0.5</beamDistance>
    <beamMinLen>1.32</beamMinLen>
    <beamNoSlope>0</beamNoSlope>
    <dotMag>1</dotMag>
    <dotNoteDistance>0.35</dotNoteDistance>
    <dotRestDistance>0.25</dotRestDistance>
    <dotDotDistance>0.5</dotDotDistance>
    <propertyDistanceHead>1</propertyDistanceHead>
    <propertyDistanceStem>1.8</propertyDistanceStem>
    <propertyDistance>1</propertyDistance>
    <articulationMag>1</articulationMag>
    <lastSystemFillLimit>0.25</lastSystemFillLimit>
    <hairpinY>7.5</hairpinY>
    <hairpinHeight>1.2</hairpinHeight>
    <hairpinContHeight>0.5</hairpinContHeight>
    <hairpinWidth>0.13</hairpinWidth>
    <pedalY>8</pedalY>
    <pedalLineWidth>0.15</pedalLineWidth>
    <pedalListStyle>1</pedalListStyle>
    <trillY>-1</trillY>
    <harmonyY>2.5</harmonyY>
    <harmonyFretDist>0.5</harmonyFretDist>
    <minHarmonyDistance>0.5</minHarmonyDistance>
    <maxHarmonyBarDistance>3</maxHarmonyBarDistance>
    <capoPosition>0</capoPosition>
    <fretNumMag>2</fretNumMag>
    <fretNumPos>0</fretNumPos>
    <fretY>2</fretY>
    <showPageNumber>1</showPageNumber>
    <showPageNumberOne>0</showPageNumberOne>
    <pageNumberOddEven>1</pageNumberOddEven>
    <showMeasureNumber>0</showMeasureNumber>
    <showMeasureNumberOne>0</showMeasureNumberOne>
    <measureNumberInterval>5</measureNumberInterval>
    <measureNumberSystem>1</measureNumberSystem>
    <measureNumberAllStaffs>0</measureNumberAllStaffs>
    <smallNoteMag>0.7</smallNoteMag>
    <graceNoteMag>0.7</graceNoteMag>
    <smallStaffMag>0.7</smallStaffMag>
    <smallClefMag>0.8</smallClefMag>
    <genClef>1</genClef>
    <genKeysig>1</genKeysig>
    <genTimesig>1</genTimesig>
    <genCourtesyTimesig>1</genCourtesyTimesig>
    <genCourtesyKeysig>1</genCourtesyKeysig>
    <genCourtesyClef>1</genCourtesyClef>
    <swingRatio>60</swingRatio>
    <swingUnit></swingUnit>
    <useStandardNoteNames>1</useStandardNoteNames>
    <useGermanNoteNames>0</useGermanNoteNames>
    <useFullGermanNoteNames>0</useFullGermanNoteNames>
    <useSolfeggioNoteNames>0</useSolfeggioNoteNames>
    <useFrenchNoteNames>0</useFrenchNoteNames>
    <automaticCapitalization>1</automaticCapitalization>
    <lowerCaseMinorChords>0</lowerCaseMinorChords>
    <lowerCaseBassNotes>0</lowerCaseBassNotes>
    <allCapsNoteNames>0</allCapsNoteNames>
    <chordStyle>jazz</chordStyle>
    <chordsXmlFile>0</chordsXmlFile>
    <chordDescriptionFile>chords_jazz.xml</chordDescriptionFile>
    <concertPitch>0</concertPitch>
    <createMultiMeasureRests>0</createMultiMeasureRests>
    <minEmptyMeasures>2</minEmptyMeasures>
    <minMMRestWidth>4</minMMRestWidth>
    <hideEmptyStaves>0</hideEmptyStaves>
    <dontHidStavesInFirstSystm>1</dontHidStavesInFirstSystm>
    <hideInstrumentNameIfOneInstrument>1</hideInstrumentNameIfOneInstrument>
    <gateTime>100</gateTime>
    <tenutoGateTime>100</tenutoGateTime>
    <staccatoGateTime>50</staccatoGateTime>
    <slurGateTime>100</slurGateTime>
    <ArpeggioNoteDistance>0.5</ArpeggioNoteDistance>
    <ArpeggioLineWidth>0.18</ArpeggioLineWidth>
    <ArpeggioHookLen>0.8</ArpeggioHookLen>
    <FixMeasureNumbers>0</FixMeasureNumbers>
    <FixMeasureWidth>0</FixMeasureWidth>
    <slurEndWidth>0.07</slurEndWidth>
    <slurMidWidth>0.15</slurMidWidth>
    <slurDottedWidth>0.1</slurDottedWidth>
    <minTieLength>1</minTieLength>
    <sectionPause>3</sectionPause>
    <musicalSymbolFont>Emmentaler</musicalSymbolFont>
    <musicalTextFont>MuseJazz</musicalTextFont>
    <showHeader>0</showHeader>
    <headerFirstPage>0</headerFirstPage>
    <headerOddEven>1</headerOddEven>
    <evenHeaderL></evenHeaderL>
    <evenHeaderC></evenHeaderC>
    <evenHeaderR></evenHeaderR>
    <oddHeaderL></oddHeaderL>
    <oddHeaderC></oddHeaderC>
    <oddHeaderR></oddHeaderR>
    <showFooter>1</showFooter>
    <footerFirstPage>1</footerFirstPage>
    <footerOddEven>0</footerOddEven>
    <evenFooterL>$p</evenFooterL>
    <evenFooterC>$:copyright:</evenFooterC>
    <evenFooterR></evenFooterR>
    <oddFooterL></oddFooterL>
    <oddFooterC>$C$p</oddFooterC>
    <oddFooterR></oddFooterR>
    <voltaY>-6</voltaY>
    <voltaHook>1.9</voltaHook>
    <voltaLineWidth>0.1</voltaLineWidth>
    <voltaLineStyle>1</voltaLineStyle>
    <ottavaY>-3</ottavaY>
    <ottavaHook>1.9</ottavaHook>
    <ottavaLineWidth>0.1</ottavaLineWidth>
    <ottavaLineStyle>2</ottavaLineStyle>
    <ottavaNumbersOnly>1</ottavaNumbersOnly>
    <tabClef>13</tabClef>
    <tremoloWidth>1.2</tremoloWidth>
    <tremoloBoxHeight>0.65</tremoloBoxHeight>
    <tremoloLineWidth>0.35</tremoloLineWidth>
    <tremoloDistance>0.8</tremoloDistance>
    <linearStretch>1.5</linearStretch>
    <crossMeasureValues>0</crossMeasureValues>
    <keySigNaturals>0</keySigNaturals>
    <tupletMaxSlope>0.5</tupletMaxSlope>
    <tupletOufOfStaff>1</tupletOufOfStaff>
    <tupletVHeadDistance>0.5</tupletVHeadDistance>
    <tupletVStemDistance>0.25</tupletVStemDistance>
    <tupletStemLeftDistance>0.5</tupletStemLeftDistance>
    <tupletStemRightDistance>0.5</tupletStemRightDistance>
    <tupletNoteLeftDistance>0</tupletNoteLeftDistance>
    <tupletNoteRightDistance>0</tupletNoteRightDistance>
    <barreLineWidth>1</barreLineWidth>
    <fretMag>1</fretMag>
    <scaleBarlines>1</scaleBarlines>
    <barGraceDistance>0.6</barGraceDistance>
    <TextStyle>
      <halign>left</halign>
      <valign>baseline</valign>
      <offsetType>spatium</offsetType>
      <family>FreeSerif</family>
      <size>10</size>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>top</valign>
      <offsetType>absolute</offsetType>
      <name>Title</name>
      <family>MuseJazz</family>
      <size>28</size>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>top</valign>
      <xoffset>0</xoffset>
      <yoffset>10</yoffset>
      <offsetType>absolute</offsetType>
      <name>Subtitle</name>
      <family>MuseJazz</family>
      <size>14</size>
      </TextStyle>
    <TextStyle>
      <halign>right</halign>
      <valign>bottom</valign>
      <offsetType>absolute</offsetType>
      <name>Composer</name>
      <family>MuseJazz</family>
      <size>12</size>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>bottom</valign>
      <offsetType>absolute</offsetType>
      <name>Lyricist</name>
      <family>MuseJazz</family>
      <size>12</size>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>baseline</valign>
      <xoffset>0</xoffset>
      <yoffset>6</yoffset>
      <offsetType>spatium</offsetType>
      <name>Lyrics Odd Lines</name>
      <family>MuseJazz</family>
      <size>11</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>baseline</valign>
      <xoffset>0</xoffset>
      <yoffset>6</yoffset>
      <offsetType>spatium</offsetType>
      <name>Lyrics Even Lines</name>
      <family>MuseJazz</family>
      <size>11</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>center</valign>
      <offsetType>absolute</offsetType>
      <name>Fingering</name>
      <family>MuseJazz</family>
      <size>8</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>right</halign>
      <valign>center</valign>
      <xoffset>-0.5</xoffset>
      <yoffset>0</yoffset>
      <offsetType>spatium</offsetType>
      <name>LH Guitar Fingering</name>
      <family>FreeSerif</family>
      <size>8</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>center</valign>
      <offsetType>spatium</offsetType>
      <name>RH Guitar Fingering</name>
      <family>FreeSerif</family>
      <size>8</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>center</valign>
      <xoffset>0</xoffset>
      <yoffset>-5</yoffset>
      <offsetType>spatium</offsetType>
      <name>String Number</name>
      <family>MuseJazz</family>
      <size>8</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      <frameWidthS>0.1</frameWidthS>
      <paddingWidthS>0.2</paddingWidthS>
      <frameRound>0</frameRound>
      <frameColor r="0" g="0" b="0" a="255"/>
      <circle>1</circle>
      </TextStyle>
    <TextStyle>
      <halign>right</halign>
      <valign>center</valign>
      <offsetType>absolute</offsetType>
      <name>Instrument Name (Long)</name>
      <family>MuseJazz</family>
      <size>12</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>right</halign>
      <valign>center</valign>
      <offsetType>absolute</offsetType>
      <name>Instrument Name (Short)</name>
      <family>MuseJazz</family>
      <size>12</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>top</valign>
      <offsetType>absolute</offsetType>
      <name>Instrument Name (Part)</name>
      <family>MuseJazz</family>
      <size>18</size>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>baseline</valign>
      <xoffset>0</xoffset>
      <yoffset>8</yoffset>
      <offsetType>spatium</offsetType>
      <name>Dynamics</name>
      <family>MuseJazz</family>
      <size>12</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>baseline</valign>
      <xoffset>0</xoffset>
      <yoffset>-2</yoffset>
      <offsetType>spatium</offsetType>
      <name>Technique</name>
      <family>MuseJazz</family>
      <size>12</size>
      <italic>1</italic>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>baseline</valign>
      <xoffset>0</xoffset>
      <yoffset>-4</yoffset>
      <offsetType>spatium</offsetType>
      <name>Tempo</name>
      <family>MuseJazz</family>
      <size>12</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      <systemFlag>1</systemFlag>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>top</valign>
      <offsetType>spatium</offsetType>
      <name>Metronome</name>
      <family>MuseJazz</family>
      <size>12</size>
      <bold>1</bold>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>bottom</valign>
      <xoffset>0</xoffset>
      <yoffset>-2</yoffset>
      <offsetType>spatium</offsetType>
      <name>Measure Number</name>
      <family>MuseJazz</family>
      <size>8</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>top</valign>
      <xoffset>0</xoffset>
      <yoffset>6</yoffset>
      <offsetType>spatium</offsetType>
      <name>Translator</name>
      <family>MuseJazz</family>
      <size>11</size>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>center</valign>
      <offsetType>absolute</offsetType>
      <name>Tuplet</name>
      <family>MuseJazz</family>
      <size>10</size>
      <italic>1</italic>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>baseline</valign>
      <xoffset>0</xoffset>
      <yoffset>-2</yoffset>
      <offsetType>spatium</offsetType>
      <name>System</name>
      <family>MuseJazz</family>
      <size>11</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      <systemFlag>1</systemFlag>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>top</valign>
      <xoffset>0</xoffset>
      <yoffset>5.5</yoffset>
      <offsetType>spatium</offsetType>
      <name>Staff</name>
      <family>MuseJazz</family>
      <size>11</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>baseline</valign>
      <offsetType>spatium</offsetType>
      <name>Chord Symbol</name>
      <family>MuseJazz</family>
      <size>15</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>right</halign>
      <valign>baseline</valign>
      <xoffset>0</xoffset>
      <yoffset>-3</yoffset>
      <offsetType>spatium</offsetType>
      <name>Rehearsal Mark</name>
      <family>MuseJazz</family>
      <size>14</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      <frameWidthS>0.2</frameWidthS>
      <paddingWidthS>0.2</paddingWidthS>
      <frameRound>20</frameRound>
      <frameColor r="0" g="0" b="0" a="255"/>
      <systemFlag>1</systemFlag>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>baseline</valign>
      <xoffset>0</xoffset>
      <yoffset>-3</yoffset>
      <offsetType>spatium</offsetType>
      <name>Repeat Text Left</name>
      <family>MuseJazz</family>
      <size>20</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      <systemFlag>1</systemFlag>
      </TextStyle>
    <TextStyle>
      <halign>right</halign>
      <valign>top</valign>
      <xoffset>0</xoffset>
      <yoffset>5.5</yoffset>
      <offsetType>spatium</offsetType>
      <name>Repeat Text Right</name>
      <family>MuseJazz</family>
      <size>12</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      <systemFlag>1</systemFlag>
      </TextStyle>
    <TextStyle>
      <halign>right</halign>
      <valign>baseline</valign>
      <xoffset>0</xoffset>
      <yoffset>-2</yoffset>
      <offsetType>spatium</offsetType>
      <name>Repeat Text</name>
      <family>MuseJazz</family>
      <size>12</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      <systemFlag>1</systemFlag>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>baseline</valign>
      <xoffset>0.5</xoffset>
      <yoffset>1.9</yoffset>
      <offsetType>spatium</offsetType>
      <name>Volta</name>
      <family>MuseJazz</family>
      <size>8</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>top</valign>
      <offsetType>spatium</offsetType>
      <name>Frame</name>
      <family>MuseJazz</family>
      <size>12</size>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>center</valign>
      <offsetType>spatium</offsetType>
      <name>Text Line</name>
      <family>MuseJazz</family>
      <size>10</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>baseline</valign>
      <offsetType>spatium</offsetType>
      <name>Glissando</name>
      <family>MuseJazz</family>
      <size>8</size>
      <italic>1</italic>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>center</valign>
      <offsetType>spatium</offsetType>
      <name>Ottava</name>
      <family>MuseJazz</family>
      <size>10</size>
      <italic>1</italic>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>center</valign>
      <offsetType>spatium</offsetType>
      <name>Bend</name>
      <family>MuseJazz</family>
      <size>8</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>top</valign>
      <offsetType>spatium</offsetType>
      <name>Header</name>
      <family>MuseJazz</family>
      <size>8</size>
      </TextStyle>
    <TextStyle>
      <halign>center</halign>
      <valign>bottom</valign>
      <xoffset>0</xoffset>
      <yoffset>5</yoffset>
      <offsetType>absolute</offsetType>
      <name>Footer</name>
      <family>MuseJazz</family>
      <size>8</size>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>bottom</valign>
      <xoffset>0</xoffset>
      <yoffset>-3</yoffset>
      <offsetType>spatium</offsetType>
      <name>Instrument Change</name>
      <family>MuseJazz</family>
      <size>12</size>
      <bold>1</bold>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <TextStyle>
      <halign>left</halign>
      <valign>top</valign>
      <xoffset>0</xoffset>
      <yoffset>6</yoffset>
      <offsetType>spatium</offsetType>
      <name>Figured Bass</name>
      <family>MScoreBC</family>
      <size>8</size>
      <sizeIsSpatiumDependent>1</sizeIsSpatiumDependent>
      </TextStyle>
    <fermataAnchor>0</fermataAnchor>
    <shortfermataAnchor>0</shortfermataAnchor>
    <longfermataAnchor>0</longfermataAnchor>
    <verylongfermataAnchor>0</verylongfermataAnchor>
    <sforzatoAnchor>2</sforzatoAnchor>
    <staccatoAnchor>2</staccatoAnchor>
    <staccatissimoAnchor>2</staccatissimoAnchor>
    <tenutoAnchor>2</tenutoAnchor>
    <portatoAnchor>2</portatoAnchor>
    <marcatoAnchor>2</marcatoAnchor>
    <fadeinAnchor>2</fadeinAnchor>
    <fadeoutAnchor>2</fadeoutAnchor>
    <volumeswellAnchor>2</volumeswellAnchor>
    <wigglesawtoothAnchor>2</wigglesawtoothAnchor>
    <wigglesawtoothwideAnchor>2</wigglesawtoothwideAnchor>
    <wigglevibratolargefasterAnchor>2</wigglevibratolargefasterAnchor>
    <wigglevibratolargeslowestAnchor>2</wigglevibratolargeslowestAnchor>
    <ouvertAnchor>0</ouvertAnchor>
    <plusstopAnchor>0</plusstopAnchor>
    <upbowAnchor>0</upbowAnchor>
    <downbowAnchor>0</downbowAnchor>
    <reverseturnAnchor>0</reverseturnAnchor>
    <turnAnchor>0</turnAnchor>
    <trillAnchor>0</trillAnchor>
    <prallAnchor>0</prallAnchor>
    <mordentAnchor>0</mordentAnchor>
    <prallprallAnchor>0</prallprallAnchor>
    <prallmordentAnchor>0</prallmordentAnchor>
    <upprallAnchor>0</upprallAnchor>
    <downprallAnchor>0</downprallAnchor>
    <upmordentAnchor>0</upmordentAnchor>
    <downmordentAnchor>0</downmordentAnchor>
    <pralldownAnchor>0</pralldownAnchor>
    <prallupAnchor>0</prallupAnchor>
    <lineprallAnchor>0</lineprallAnchor>
    <schleiferAnchor>0</schleiferAnchor>
    <snappizzicatoAnchor>0</snappizzicatoAnchor>
    <thumbAnchor>0</thumbAnchor>
    <lutefingeringthumbAnchor>4</lutefingeringthumbAnchor>
    <lutefingering1stAnchor>4</lutefingering1stAnchor>
    <lutefingering2ndAnchor>4</lutefingering2ndAnchor>
    <lutefingering3rdAnchor>4</lutefingering3rdAnchor>
    <page-layout>
      <page-height>1683.36</page-height>
      <page-width>1190.88</page-width>
      <page-margins type="even">
        <left-margin>56.6929</left-margin>
        <right-margin>57.0217</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      <page-margins type="odd">
        <left-margin>56.6929</left-margin>
        <right-margin>57.0217</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      </page-layout>
    <Spatium>1.85</Spatium>
    </Style>
  </museScore>
