#!/bin/sh

#
# "compare" - image magick compare program
#
SRC="mmrest-1 bravura-mmrest mmrest-2 mmrest-4 mmrest-5 mmrest-6 mmrest-7 mmrest-8 mmrest-9\
 fmrest-1 fmrest-2 fmrest-3 fmrest-4 fmrest-5 fmrest-6 measure-repeat-1 \
 noteheadposition-1 valign-1 emmentaler-1 bravura-1 emmentaler-2 bravura-2\
 emmentaler-3 bravura-3 emmentaler-4 bravura-4 emmentaler-5 bravura-5\
 emmentaler-6 bravura-6 emmentaler-7 bravura-7\
 emmentaler-8 bravura-8 emmentaler-9 bravura-9 emmentaler-10 bravura-10"
# SRC="emmentaler-8 bravura-8"

MSCORE=../build.debug/mscore/mscore
DPI=130
F=vtest.html

rm -rf html
mkdir html
cd html

for src in $SRC; do
      echo process ../$src
      cp ../$src-ref.png .
      ../$MSCORE ../$src.mscz -r $DPI -o $src.png
      compare $src-1.png $src-ref.png $src-diff.png
      done

cp -f ../style.css .

rm -f $F
echo "<html>" >> $F
echo "  <head>" >> $F
echo "   <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">" >> $F
echo "  </head>" >> $F
echo "  <body>" >> $F
echo "    <div id=\"topbar\">" >> $F
echo "      <span>Current</span>" >> $F
echo "      <span>Reference</span>" >> $F
echo "      <span>Comparison</span>" >> $F
echo "    </div>" >> $F
echo "    <div id=\"topmargin\"></div>" >> $F
for src in $SRC; do
      echo "    <h2 id=\"$src\">$src <a class=\"toc-anchor\" href=\"#$src\">#</a></h2>" >> $F
      echo "    <div>" >> $F
      echo "      <img src=\"$src-1.png\">" >> $F
      echo "      <img src=\"$src-ref.png\">" >> $F
      echo "      <img src=\"$src-diff.png\">" >> $F
      echo "    </div>" >> $F
      done
echo "  </body>" >> $F
echo "</html>" >> $F


konqueror $F

