#!/bin/bash

cp ../../../build.debug/mtest/libmscore/selectionfilter/selectionfilter6-base.xml selectionfilter6-base-ref.xml
cp ../../../build.debug/mtest/libmscore/selectionfilter/selectionfilter8-base.xml selectionfilter8-base-ref.xml
cp ../../../build.debug/mtest/libmscore/selectionfilter/selectionfilter9-base.xml selectionfilter9-base-ref.xml

