/*
 * SPDX-License-Identifier: GPL-3.0-only
 * MuseScore-Studio-CLA-applies
 *
 * MuseScore Studio
 * Music Composition & Notation
 *
 * Copyright (C) 2026 MuseScore Limited and others
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <gtest/gtest.h>

#include <QByteArray>

#include "engraving/dom/masterscore.h"
#include "engraving/dom/measure.h"
#include "engraving/dom/part.h"
#include "engraving/dom/chord.h"
#include "engraving/dom/note.h"
#include "engraving/dom/rest.h"
#include "engraving/dom/segment.h"
#include "engraving/dom/tie.h"

#include "importexport/encore/internal/parser/zbot.h"

#include "testbase.h"

static const QString ENC_DIR(QString(iex_encore_tests_DATA_ROOT) + "/data/");

using namespace mu::engraving;
using namespace mu::iex::enc;

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

static Measure* measureAt(MasterScore* score, int n)
{
    int idx = 0;
    for (MeasureBase* mb = score->first(); mb; mb = mb->next()) {
        if (mb->isMeasure()) {
            if (idx++ == n) {
                return toMeasure(mb);
            }
        }
    }
    return nullptr;
}

// ---------------------------------------------------------------------------
// Unit tests: stream cipher
// ---------------------------------------------------------------------------

TEST(ZbotCipher, isZbotMagic_accepts_all_three_variants)
{
    EXPECT_TRUE(isZbotMagic(QByteArray("ZBOT")));
    EXPECT_TRUE(isZbotMagic(QByteArray("ZBOP")));
    EXPECT_TRUE(isZbotMagic(QByteArray("ZBO6")));
}

TEST(ZbotCipher, isZbotMagic_rejects_scow_and_others)
{
    EXPECT_FALSE(isZbotMagic(QByteArray("SCOW")));
    EXPECT_FALSE(isZbotMagic(QByteArray("SCO5")));
    EXPECT_FALSE(isZbotMagic(QByteArray("")));
    EXPECT_FALSE(isZbotMagic(QByteArray("ZBTX")));
}

TEST(ZbotCipher, decrypts_carnavalito_header_to_scow)
{
    // First 8 bytes of carnavalito.zbot.enc, extracted from the file.
    // Expected output verified by the reference Python decryptor.
    QByteArray encrypted("\x5A\x42\x4F\x54\xC5\x06\x04\x05", 8);
    QByteArray expected("\x53\x43\x4F\x57\xC4\x00\x00\x00", 8);

    zbotDecrypt(encrypted);

    EXPECT_EQ(encrypted, expected);
    // Byte 0-3 must decode to "SCOW"
    EXPECT_EQ(encrypted.left(4), QByteArray("SCOW"));
    // Byte 4 is the format magic; for Carnavalito it is 0xC4 (v0xC4)
    EXPECT_EQ(static_cast<quint8>(encrypted[4]), 0xC4u);
}

TEST(ZbotCipher, double_decrypt_is_identity)
{
    // XOR stream cipher applied twice restores the original.
    QByteArray original("\x5A\x42\x4F\x54\xC5\x06\x04\x05", 8);
    QByteArray buf = original;
    zbotDecrypt(buf);
    zbotDecrypt(buf);
    EXPECT_EQ(buf, original);
}

TEST(ZbotCipher, decrypt_empty_buffer_is_no_op)
{
    QByteArray buf;
    zbotDecrypt(buf);
    EXPECT_TRUE(buf.isEmpty());
}

// ---------------------------------------------------------------------------
// Integration tests: importEncore on synthetic ZBOT files
// (generated by gen_enc_test_files.py from the bazo.enc skeleton)
// ---------------------------------------------------------------------------

class Tst_Zbot : public ::testing::Test, public MTest
{
protected:
    void SetUp() override { setRootDir(ENC_DIR); }
};

// Minimal SCOW v0xC4 file with one C4 quarter note, encrypted as ZBOT.
// Verifies the decrypt-then-parse pipeline on a known-content file.
TEST_F(Tst_Zbot, zbot_single_note_loads_and_has_measures)
{
    MasterScore* score = readEncoreScore("zbot_single_note.enc");
    ASSERT_NE(score, nullptr);
    EXPECT_GT(score->nmeasures(), 0);
    delete score;
}

// Coverage: encrypted files are a quarter of the corpus and the two fixtures above carry between
// them one note and one skeleton. This one holds a whole element family, so it exercises the
// decryption and then the generation-dependent offsets underneath it: the plaintext it unwraps
// states format 3.07, where every element body sits two bytes later than in the generation before.
TEST_F(Tst_Zbot, zbot_element_family_survives_decryption)
{
    MasterScore* score = readEncoreScore("zbot_family_40x.enc");
    ASSERT_NE(score, nullptr);
    muse::Ret ret = score->sanityCheck();
    EXPECT_TRUE(ret) << ret.text();

    Measure* m = score->firstMeasure();
    ASSERT_NE(m, nullptr);

    std::vector<int> pitches;
    int rests = 0, ties = 0;
    for (Segment* seg = m->first(SegmentType::ChordRest); seg; seg = seg->next(SegmentType::ChordRest)) {
        EngravingItem* el = seg->element(0);
        if (!el) {
            continue;
        }
        if (el->isRest()) {
            ++rests;
        } else if (el->isChord()) {
            for (Note* n : toChord(el)->notes()) {
                pitches.push_back(n->pitch());
                if (n->tieFor()) {
                    ++ties;
                }
            }
        }
    }
    EXPECT_EQ(pitches, (std::vector<int> { 60, 60, 62 }));
    EXPECT_EQ(ties, 1);
    EXPECT_EQ(rests, 1);

    delete score;
}

// bazo.enc content encrypted as ZBOT must produce the same score as plain bazo.enc.
TEST_F(Tst_Zbot, zbot_from_bazo_matches_plain_bazo)
{
    MasterScore* plain = readEncoreScore("bazo.enc");
    ASSERT_NE(plain, nullptr);

    MasterScore* zbot = readEncoreScore("zbot_from_bazo.enc");
    ASSERT_NE(zbot, nullptr);

    EXPECT_EQ(zbot->nmeasures(), plain->nmeasures());
    EXPECT_EQ(zbot->parts().size(), plain->parts().size());

    delete plain;
    delete zbot;
}

// The macOS side of the wrapper. A ZBO6 container is a SCO5 document under the same keystream, which
// is why encrypting one turns its magic into ZBO6 by itself: seventeen real files behave this way and
// every one of them decrypts to a big-endian format 4.20 score. The decrypted file must therefore
// import exactly like the plain one, byte order included.
TEST_F(Tst_Zbot, zbo6_container_decrypts_to_a_macos_score)
{
    QByteArray head("\x5A\x42\x4F\x36", 4);
    zbotDecrypt(head);
    EXPECT_EQ(head, QByteArray("SCO5")) << "the keystream carries ZBO6 to SCO5";

    MasterScore* plain = readEncoreScore("structure_sco5_macos.enc");
    MasterScore* encrypted = readEncoreScore("zbo6_from_sco5.enc");
    ASSERT_NE(encrypted, nullptr) << "the encrypted macOS container must import";
    ASSERT_NE(plain, nullptr);

    EXPECT_EQ(encrypted->nmeasures(), plain->nmeasures());
    EXPECT_EQ(encrypted->parts().size(), plain->parts().size());

    delete plain;
    delete encrypted;
}
