name: Clear release info

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Mode: stable, testing(alpha, beta, rc)'
        required: true
        default: 'testing'

defaults:
  run:
    shell: bash

jobs:
  update-release-clear:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Clear info about the latest release in musescore-updates
        run: |
          S3_URL="s3://musescore-updates/feed/latest.xml"
          if [ ${{ github.event.inputs.mode }} == "testing" ]; then
            S3_URL="s3://musescore-updates/feed/latest.test.xml"
          fi

          sudo bash ./build/ci/release/make_empty_release_info_file.sh

          sudo bash ./build/ci/release/push_file_to_s3.sh \
            --s3_key ${{ secrets.S3_KEY_UPDATE }} \
            --s3_secret ${{ secrets.S3_SECRET_UPDATE }} \
            --s3_url ${S3_URL} \
            --s3_bucket ${{ secrets.S3_BUCKET_UPDATE }} \
            --file_name "release_info.json"
