name: 'Update: Release Info (clear)'

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Mode: stable, testing(alpha, beta, rc)'
        required: true
        default: 'testing'

defaults:
  run:
    shell: bash

jobs:
  update-release-clear:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Clear info about the latest release in musescore-updates
        run: |
          S3_URL="s3://musescore-updates/feed/latest.xml"
          if [ ${{ inputs.mode }} == "testing" ]; then
            S3_URL="s3://musescore-updates/feed/latest.test.xml"
          fi

          bash ./buildscripts/ci/release/make_empty_release_info_file.sh

          bash ./buildscripts/ci/tools/s3_push_file.sh \
            --s3_key ${{ secrets.S3_KEY_UPDATE }} \
            --s3_secret ${{ secrets.S3_SECRET_UPDATE }} \
            --s3_url ${S3_URL} \
            --s3_bucket ${{ secrets.S3_BUCKET_UPDATE }} \
            --file_name "build.artifacts/release_info.json"
